import { storeToRefs } from "pinia";
import { defineStore } from "pinia";
import { useAtriumAppStore } from "./atrium-app.js";

export const useDashboardStore = defineStore("atrium-dashboard", () => {
  const app = useAtriumAppStore();
  const {
    canManage,
    currentSpace,
    dashboardAddOpen,
    dashboardDragGhost,
    dashboardDragging,
    dashboardEditAdvanced,
    dashboardEditDirty,
    dashboardEditForm,
    dashboardEditPanelStyle,
    dashboardEditSelectedId,
    dashboardEditorBlocks,
    dashboardEditorSaving,
    dashboardEditorSpace,
    dashboardLoading,
    dashboardPreviewRole,
    showDashboardEditor
  } = storeToRefs(app);

  return {
    addBlockFromPicker: app.addBlockFromPicker,
    addDashboardBlock: app.addDashboardBlock,
    applyDashboardEditForm: app.applyDashboardEditForm,
    blockDataCount: app.blockDataCount,
    blockDataFor: app.blockDataFor,
    blockOrderMapForSpace: app.blockOrderMapForSpace,
    blockOrderMapFromBlocks: app.blockOrderMapFromBlocks,
    blockStyle: app.blockStyle,
    blockTitle: app.blockTitle,
    blockTypeCards: app.blockTypeCards,
    blockTypeIs: app.blockTypeIs,
    blockTypeLabel: app.blockTypeLabel,
    blockTypeOptions: app.blockTypeOptions,
    blockTypes: app.blockTypes,
    blocksForSpace: app.blocksForSpace,
    canManage,
    clearDashboardEditSelection: app.clearDashboardEditSelection,
    closeAddBlockPicker: app.closeAddBlockPicker,
    closeDashboardEditor: app.closeDashboardEditor,
    closeInlineEdit: app.closeInlineEdit,
    currentSpace,
    dashboardAddOpen,
    dashboardDragGhost,
    dashboardDragging,
    dashboardEditAdvanced,
    dashboardEditDirty,
    dashboardEditForm,
    dashboardEditPanelStyle,
    dashboardEditSelectedId,
    dashboardEditorBlocks,
    dashboardEditorSaving,
    dashboardEditorSpace,
    dashboardLoading,
    dashboardPreviewRole,
    deleteDashboardBlockDraft: app.deleteDashboardBlockDraft,
    enableV0Editor: app.enableV0Editor,
    hasDashboard: app.hasDashboard,
    inlineAddForm: app.inlineAddForm,
    inlineEditAdvanced: app.inlineEditAdvanced,
    inlineEditBlock: app.inlineEditBlock,
    inlineEditForm: app.inlineEditForm,
    inlineEditPopover: app.inlineEditPopover,
    isDashboardEditing: app.isDashboardEditing,
    isResourcesBlock: app.isResourcesBlock,
    onDashboardPreviewRoleChange: app.onDashboardPreviewRoleChange,
    openAddBlockPicker: app.openAddBlockPicker,
    openDashboardEditor: app.openDashboardEditor,
    saveBlockSettings: app.saveBlockSettings,
    saveDashboardEditor: app.saveDashboardEditor,
    saveDashboardLayout: app.saveDashboardLayout,
    saveInlineContent: app.saveInlineContent,
    setDashboardEditSelection: app.setDashboardEditSelection,
    setDashboardPreviewRole: app.setDashboardPreviewRole,
    showDashboardEditor,
    stopDashboardEdit: app.stopDashboardEdit,
    toggleDashboardEdit: app.toggleDashboardEdit,
    toggleDashboardEditAdvanced: app.toggleDashboardEditAdvanced,
    toggleInlineEditAdvanced: app.toggleInlineEditAdvanced
  };
});
