import { Bookmark } from "lucide-vue-next";
import { PLATFORM_FALLBACK_LANG } from "./platform/i18n/index.js";

export const HOTKEYS = {
  next: "D / →",
  prev: "A / ←",
  help: "?"
};

export const FALLBACK_LANG = PLATFORM_FALLBACK_LANG;
export const LANG_STORAGE_KEY = "atrium:lang";
export const ENABLE_V0_EDITOR = false;
export const ENABLE_V0_DEV_ADMIN_SEAMS = false;
export const ENABLE_V0_RESOURCE_DETAILS = false;

export const MESSAGES = {
  en: {
    "app.title": "Atrium",
    "app.spaces": "Spaces",
    "app.switchContext": "Switch your context",
    "app.searchSpaces": "Search spaces",
    "app.noSpaces": "No spaces yet.",
    "app.login": "Login",
    "app.language": "Language",
    "app.logout": "Log out",
    "app.settings": "Settings",
    "app.theme": "Theme",
    "app.themeDark": "Dark",
    "app.themeLight": "Light",
    "app.themeAuto": "Auto",
    "app.home": "Home",
    "app.privacy": "Privacy",
    "app.adminPanel": "Admin Panel",
    "app.back": "Back",
    "app.close": "Close",
    "app.addBlock": "Add block",
    "app.addBlockShort": "Add",
    "app.save": "Save",
    "app.saveDashboard": "Save dashboard",
    "app.cancel": "Cancel",
    "app.editLayout": "Edit layout",
    "app.exit": "Exit",
    "app.details": "Details",
    "app.keyboardShortcuts": "Keyboard Shortcuts",
    "assistant.tabs.ariaLabel": "Assistant sections",
    "assistant.tabs.chat": "Chat",
    "assistant.tabs.capabilities": "Capabilities",
    "assistant.tabs.routines": "Routines",
    "assistant.tabs.artifacts": "Artifacts",
    "assistant.tabs.pages": "Pages",
    "assistant.sidebar.expand": "Expand sidebar",
    "assistant.sidebar.collapse": "Collapse sidebar",
    "assistant.sidebar.newChat": "New chat",
    "assistant.sidebar.searchPlaceholder": "Search chats",
    "assistant.sidebar.loadingChats": "Loading chats...",
    "assistant.sidebar.emptyChats": "Your chats will appear here.",
    "assistant.sidebar.searchEmpty": "No chats found",
    "assistant.sidebar.trash": "Trash",
    "assistant.sidebar.loading": "Loading...",
    "assistant.sidebar.trashEmpty": "Trash is empty.",
    "assistant.sidebar.capabilitiesFiltersSoon": "Filters will appear in Wave 2.",
    "assistant.sidebar.routinesFiltersSoon": "Filters will appear in Wave 3.",
    "assistant.sidebar.resize": "Resize sidebar",
    "assistant.sidebar.untitled": "Untitled",
    "assistant.sidebar.openMenu": "Open chat menu",
    "assistant.sidebar.rename": "Rename",
    "assistant.sidebar.delete": "Delete",
    "assistant.sidebar.restore": "Restore",
    "assistant.sidebar.group.today": "Today",
    "assistant.sidebar.group.yesterday": "Yesterday",
    "assistant.sidebar.group.week": "Last 7 days",
    "assistant.sidebar.group.month": "Last 30 days",
    "assistant.sidebar.group.older": "Older",
    "assistant.composer.disabled": "Assistant is disabled",
    "assistant.composer.placeholder": "Message... (Enter to send, Shift+Enter for newline)",
    "assistant.composer.send": "Send message",
    "assistant.composer.stop": "Stop generating",
    "assistant.composer.modelMissing": "{id} (unavailable)",
    "assistant.composer.noModel": "No model selected",
    "assistant.composer.defaultForNew": "Default for new chats",
    "assistant.conversation.loading": "Loading chat...",
    "assistant.conversation.today": "Today",
    "assistant.conversation.yesterday": "Yesterday",
    "assistant.empty.subtitle": "Ask anything or start with a suggestion.",
    "assistant.empty.providerNotice": "The operator configures the model: it may be a third-party provider with its own processing and retention rules.",
    "assistant.empty.reliabilityNotice": "AI can be wrong. Do not treat answers as verified facts without checking.",
    "assistant.suggestion.explainCode": "Explain code",
    "assistant.suggestion.generateIdea": "Generate an idea",
    "assistant.suggestion.helpEmail": "Help with an email",
    "assistant.suggestion.summarize": "Summarize",
    "assistant.status.creating": "Creating run...",
    "assistant.status.queued": "Request queued...",
    "assistant.status.running": "Model started processing...",
    "assistant.status.receiving": "Model is responding...",
    "assistant.status.cancelling": "Stopping generation...",
    "assistant.status.reconnecting": "Reconnecting stream...",
    "assistant.latency.thinking": "Thinking {time}",
    "assistant.latency.answering": "Answering {time} · thought {thinking}",
    "assistant.latency.completed": "Answered in {total}",
    "assistant.latency.completedWithThinking": "Answered in {total} · thought {thinking}",
    "assistant.undo.pending": "Deleting in 5 seconds",
    "assistant.undo.cancel": "Undo",
    "assistant.dialog.renameTitle": "New chat title",
    "assistant.dialog.deleteConfirm": "Delete chat \"{title}\"? You can restore it from Trash.",
    "assistant.message.proposalOne": "Ready to run {name}",
    "assistant.message.proposalBatch": "Ready to run batch: {names}",
    "assistant.message.awaitingApproval": "awaiting approval",
    "assistant.message.statusApproved": "approved",
    "assistant.message.statusRejected": "rejected",
    "assistant.message.statusCancelled": "cancelled",
    "assistant.message.approve": "Run",
    "assistant.message.reject": "Reject",
    "assistant.message.surfacePatchSummary": "{pageKind} · changes: {count}",
    "assistant.message.surfacePatchApply": "Apply to {pageKind}",
    "assistant.message.surfacePatchReject": "Reject",
    "assistant.message.surfacePatchApplied": "Applied",
    "assistant.message.surfacePatchRejected": "Rejected",
    "assistant.message.surfacePatchOpen": "Open page",
    "assistant.message.surfacePatchHint": "Creates a new page version you can open and edit afterwards.",
    "assistant.message.surfacePatchOp.addBlock": "+ block {block} in {region}",
    "assistant.message.surfacePatchOp.removeBlock": "− block {blockRef}",
    "assistant.message.surfacePatchOp.setProps": "changed properties {blockRef}",
    "assistant.message.surfacePatchOp.moveBlock": "{blockRef}: {fromRegion} → {toRegion}",
    "assistant.message.surfacePatchOp.setLayout": "layout → {layout}",
    "assistant.message.changeLayout": "Change skill layout",
    "assistant.message.copy": "Copy message",
    "assistant.message.copyCode": "Copy",
    "assistant.message.copiedCode": "Copied",
    "assistant.message.regenerate": "Regenerate response",
    "assistant.message.retry": "Retry",
    "assistant.message.deletePair": "Delete message pair",
    "assistant.message.stopped": "Generation stopped.",
    "assistant.message.thinking": "Reasoning",
    "assistant.step.skillProposal": "Preparing {skill}",
    "assistant.step.skillRun": "Running {skill}",
    "assistant.step.unknown": "Assistant step",
    "assistant.step.status.running": "running",
    "assistant.step.status.completed": "done",
    "assistant.step.status.failed": "failed",
    "assistant.step.status.unknown": "unknown",
    "assistant.layout.compact": "Compact",
    "assistant.layout.cards": "Cards",
    "assistant.capabilities.intro": "Void Assistant capabilities are shipped code. Skills cannot be edited or deleted from the UI: each card shows what will happen when it runs and how to ask for it in chat.",
    "assistant.capabilities.loading": "Loading catalog...",
    "assistant.capabilities.empty": "The catalog is empty: no skills have shipped yet.",
    "assistant.capabilities.noResults": "Nothing matched the current filters.",
    "assistant.capabilities.resetFilters": "Reset filters",
    "assistant.capabilities.filterSummary": "{count} skills in the catalog. Filters will appear when the catalog becomes more diverse.",
    "assistant.filters.all": "All",
    "assistant.filters.stage": "Stage",
    "assistant.filters.stageValue": "Stage {value}",
    "assistant.filters.domain": "Domain",
    "assistant.filters.output": "Output",
    "assistant.filters.trustClass": "Trust class",
    "assistant.filters.status": "Status",
    "assistant.filters.enabled": "Enabled",
    "assistant.filters.paused": "Paused",
    "assistant.filters.trigger": "Trigger",
    "assistant.filters.autonomy": "Autonomy",
    "assistant.skill.trust.trusted_graph": "reads Void data",
    "assistant.skill.trust.untrusted_web": "reads public web",
    "assistant.skill.trust.trusted_user_input": "uses your input",
    "assistant.skill.trust.proposed_kadath": "prepares a graph change",
    "assistant.skill.trust.untrusted_external_mcp": "reads an external service",
    "assistant.skill.trust.untrusted_sensor": "reads an external signal",
    "assistant.skill.trust.unknown": "needs source review",
    "assistant.skill.evalPassed": "Verified in release",
    "assistant.skill.evalNeedsReview": "Needs review",
    "assistant.skill.version": "Skill · version {version}",
    "assistant.skill.source": "Source",
    "assistant.skill.result": "Result",
    "assistant.skill.restrictions": "Restrictions",
    "assistant.skill.call": "How to call",
    "assistant.skill.sayInChat": "Say in chat: \"{phrase}\".",
    "assistant.skill.launchExplain": "The button below opens a ready confirmation card for this skill.",
    "assistant.skill.details": "Technical details",
    "assistant.skill.footer": "The run starts only after confirmation in chat.",
    "assistant.skill.openInChat": "Open run in chat",
    "assistant.skill.openInChatTitle": "Opens chat and prepares a confirmation card. The skill starts only after confirmation.",
    "assistant.skill.source.http": "reads public web sources",
    "assistant.skill.source.none": "reads no external sources",
    "assistant.skill.source.allowed": "reads allowed sources",
    "assistant.skill.result.digest": "creates a digest in chat",
    "assistant.skill.result.none": "writes nothing",
    "assistant.skill.result.structured": "creates a structured result",
    "assistant.skill.restrictions.none": "no forbidden actions",
    "assistant.skill.invoke.digest_hackernews": "give me a Hacker News digest",
    "assistant.skill.invoke.digest_github": "give me a trending GitHub repositories digest",
    "assistant.skill.invoke.default": "run {name}",
    "assistant.template.enabled": "routine enabled",
    "assistant.template.notEnabled": "not enabled",
    "assistant.template.view": "View routine",
    "assistant.template.enable": "Enable",
    "assistant.routines.title": "Routines",
    "assistant.routines.intro": "These are your configured assistant programs: ContractInstance per owner. To create a new one, ask in Chat or choose a template from Capabilities.",
    "assistant.routines.newFromTemplate": "From template...",
    "assistant.routines.loading": "Loading...",
    "assistant.routines.emptyTitle": "Nothing configured yet",
    "assistant.routines.emptyText": "Create a routine through Chat or use \"From template\" above.",
    "assistant.routines.noResults": "Nothing matched the current filters.",
    "assistant.routines.resetFilters": "Reset filters",
    "assistant.routine.pause": "Pause routine",
    "assistant.routine.enable": "Enable routine",
    "assistant.routine.paused": "paused",
    "assistant.routine.lastRun": "last run: {value}",
    "assistant.routine.next": "next: {value}",
    "assistant.routine.never": "never run",
    "assistant.routine.justNow": "just now",
    "assistant.routine.hoursAgo": "{count}h ago",
    "assistant.routine.daysAgo": "{count}d ago",
    "assistant.routine.runs": "Runs",
    "assistant.routine.edit": "Edit",
    "assistant.routine.more": "More",
    "assistant.routine.drawer.create": "New routine",
    "assistant.routine.drawer.edit": "Edit routine",
    "assistant.routine.drawer.inspect": "Routine · inspect",
    "assistant.routine.drawer.untitled": "Untitled",
    "assistant.routine.drawer.displayName": "Display name",
    "assistant.routine.drawer.displayNamePlaceholder": "for example: Weekly shopping run",
    "assistant.routine.drawer.skill": "Skill",
    "assistant.routine.drawer.skillNote": "Skill cannot be changed on an existing routine: that creates a new routine because skill_version_pin must stay coherent with run history.",
    "assistant.routine.drawer.trigger": "Trigger",
    "assistant.routine.drawer.triggerPlaceholder": "for example: Sunday 10:00",
    "assistant.routine.drawer.autonomy": "Autonomy level",
    "assistant.routine.drawer.autonomyNote": "Bound above by the operator-declared template. The instance can only lower the level.",
    "assistant.routine.drawer.cancel": "Cancel",
    "assistant.routine.drawer.close": "Close",
    "assistant.routine.drawer.save": "Save",
    "assistant.routine.drawer.saving": "Saving...",
    "assistant.routine.drawer.createAction": "Create routine",
    "assistant.block.unknown": "Unsupported block: {type}",
    "assistant.metric.score": "points",
    "assistant.metric.descendants": "comments",
    "assistant.newspaper.lead": "Lead",
    "assistant.newspaper.secondary": "Secondary stories",
    "assistant.newspaper.rail": "More stories",
    "assistant.report.back": "Back to Assistant",
    "assistant.report.title": "Newspaper issue",
    "assistant.report.assembledAt": "Assembled {value}",
    "assistant.report.loading": "Loading issue...",
    "assistant.report.fetchFailed": "Failed to load issue.",
    "assistant.report.empty": "Issue is not available.",
    "assistant.report.provenance": "Issue provenance",
    "assistant.report.schema": "Schema",
    "assistant.report.sources": "Source runs",
    "assistant.report.policy": "Editorial policy",
    "assistant.artifact.open": "Open",
    "artifact.back": "Back",
    "artifact.loading": "Loading artifact...",
    "artifact.empty": "Artifact not found.",
    "artifact.error.missing_id": "Artifact id is missing in the URL.",
    "artifact.error.fetch_failed": "Failed to load artifact.",
    "artifact.error.unsupported_schema": "Unsupported artifact schema: {schema}",
    "artifact.newspaper.default_title": "Newspaper",
    "artifact.newspaper.total_count": "{count} items",
    "artifact.newspaper.sort.top_score": "Sorted by score",
    "artifact.newspaper.sort.recent": "Sorted by recency",
    "artifact.list.title": "Artifacts",
    "artifact.list.empty": "No artifacts yet. Run a skill from chat to create one.",
    "artifact.list.loading": "Loading artifacts...",
    "artifact.list.load_more": "Load more",
    "artifact.list.fetch_failed": "Failed to load artifacts.",
    "artifact.list.delete": "Delete",
    "artifact.list.delete_confirm": "Delete this artifact? This cannot be undone.",
    "artifact.list.delete_failed": "Failed to delete artifact.",
    "pages.list.title": "Pages",
    "pages.list.subtitle": "Built-in pages and the ones you customized.",
    "pages.list.empty": "No pages yet.",
    "pages.list.loading": "Loading pages...",
    "pages.list.fetch_failed": "Failed to load pages.",
    "pages.list.open": "Open",
    "pages.list.source.shipped": "Built-in",
    "pages.list.source.custom": "Custom",
    "pages.list.customized": "Customized",
    "pages.list.customized_version": "Customized · v{version}",
    "pages.list.updated_at": "Updated {date}",
    "artifact.bridge.title_fallback": "Skill artifact",
    "artifact.bridge.open_fullscreen": "Open fullscreen",
    "artifact.bridge.empty.default": "No artifact available yet.",
    "artifact.bridge.empty.no_run": "No matching skill run yet — trigger the skill to populate.",
    "artifact.bridge.empty.schema_mismatch": "Latest run has a different artifact schema.",
    "artifact.bridge.empty.routine_pending": "Routine-based lookups are coming in M3.",
    "artifact.bridge.empty.invalid_query": "Block configuration is invalid.",
    "surface.render.default_title": "Custom surface",
    "surface.render.back": "Back",
    "surface.render.loading": "Loading surface...",
    "surface.render.empty": "No saved surface for this page yet. Compose one first.",
    "surface.render.error": "Failed to load surface.",
    "surface.render.unsupported_block": "Unsupported block: {block}",
    "surface.metric.field.totalItems": "Total items",
    "surface.metric.field.lowStockCount": "Low stock",
    "surface.metric.field.missingCount": "Missing",
    "surface.metric.field.recentChangesCount": "Recent changes",
    "surface.table.empty": "No items to show.",
    "surface.table.column.name": "Name",
    "surface.table.column.sku": "SKU",
    "surface.table.column.location": "Location",
    "surface.table.column.quantity": "Quantity",
    "surface.table.column.status": "Status",
    "surface.table.column.updatedAt": "Updated",
    "surface.tree.empty": "No locations to show.",
    "surface.timeline.empty": "No recent changes.",
    "surface.low_stock.title": "Low stock",
    "surface.low_stock.empty": "Nothing to restock.",
    "surface.filter.title": "Filters",
    "surface.filter.empty": "No filters enabled.",
    "surface.filter.option.status": "Status",
    "surface.filter.option.location": "Location",
    "surface.filter.option.lowStockOnly": "Low stock only",
    "surface.filter.option.search": "Search",
    "nav.artifacts": "Artifacts",
    "app.shortcutsNavigateTitle": "Navigate spaces",
    "app.shortcutsNavigateBody": "Move between workspaces",
    "app.shortcutsHelpTitle": "Help",
    "app.shortcutsHelpBody": "Show shortcuts overlay",
    "app.loading": "Loading",
    "app.noAccessSpaces": "No spaces available for {role}.",
    "app.noAccessTitle": "No spaces have been published for your role yet.",
    "app.noAccessBody": "Atrium is active, but the operator has not assigned a shared or personal space for this account yet.",
    "app.noAccessRoleTitle": "Current role",
    "app.noAccessHelpTitle": "What to do next",
    "app.noAccessHelpBody": "If you should already have access, contact the operator or sign out and try another account.",
    "app.noAccessTrustTitle": "Why the screen stays empty",
    "auth.title": "Sign in to Atrium",
    "auth.subtitle": "Sign-in is available only when Atrium authentication is configured.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.continue": "Continue",
    "auth.signingIn": "Signing in...",
    "auth.devQuick": "Dev quick login",
    "auth.signInAs": "Sign in as {email}",
    "auth.sso": "Sign in with SSO",
    "auth.ssoHint": "Continue through the configured OIDC provider.",
    "auth.returnHint": "After sign-in you'll return to {next}.",
    "auth.unavailable": "Sign-in is not configured for this Atrium.",
    "auth.unavailableHint": "OIDC is not configured and local sign-in is unavailable.",
    "auth.loginFailed": "Login failed",
    "auth.logoutFailed": "Logout failed",
    "auth.requiredTitle": "Authentication Required",
    "auth.requiredBody": "Sign in to access the workspace.",
    "guest.title": "Your Atrium",
    "guest.body": "This is the entry to your local space. After sign-in, your services, pages, and places appear here.",
    "guest.availableTitle": "Nothing public yet",
    "guest.availableNone": "Open spaces have not been added yet.",
    "guest.trustNote": "Personal and private spaces are shown only after sign-in.",
    "guest.loginCta": "Sign in",
    "guest.contactTitle": "Next",
    "guest.contactBody": "Sign in to see your spaces and available sections.",
    "guest.valueTitle": "What it is",
    "guest.valueBody": "Atrium keeps the important things in one place instead of scattering them across separate links.",
    "guest.controlTitle": "Under your control",
    "guest.controlBody": "Data and access stay on your side.",
    "guest.accessStepsTitle": "How to sign in",
    "guest.accessStepsBody": "Sign in with your account to see the spaces available to you.",
    "guest.publicShellTitle": "Public spaces",
    "guest.publicShellSubtitle": "Only the spaces marked public_readonly are visible here.",
    "spaces.welcomeTitle": "Welcome to Atrium",
    "spaces.welcomeBody": "Create your first space to get started.",
    "spaces.publicIntroTitle": "Public access",
    "spaces.publicIntroSubtitle": "Read-only spaces available before sign-in.",
    "spaces.publicHelp": "Public info and contact details set by the operator.",
    "spaces.family": "Family",
    "spaces.familyDesc": "Home, Kids, Admin",
    "spaces.openAdmin": "Open admin",
    "spaces.adminHint": "Admin opens a read-only operator surface with real resources and entry points.",
    "admin.title.overview": "Admin",
    "admin.subtitle.overview": "Read-only operator overview built from the published admin resources.",
    "admin.title.spaces": "Spaces",
    "admin.subtitle.spaces": "Manage Atrium spaces while comparing editable state against the canonical provisioning read model.",
    "admin.title.members": "Members",
    "admin.subtitle.members": "Memberships and role assignment remain mutable while role semantics are already informed by the canonical provisioning catalog.",
    "admin.title.content": "Content",
    "admin.subtitle.content": "Provisioned directory reads are shown alongside the remaining neutral mutation surface.",
    "admin.title.dashboard": "Dashboard",
    "admin.subtitle.dashboard": "Dashboard editing remains transitional, but the admin shell can already inspect spaces that are being read through provisioning artifacts.",
    "admin.spaces.create": "New space",
    "admin.spaces.createAction": "Create space",
    "admin.spaces.active": "Active spaces",
    "admin.spaces.archived": "Archived spaces",
    "admin.spaces.edit": "Edit",
    "admin.spaces.archive": "Archive",
    "admin.spaces.restore": "Restore",
    "admin.spaces.delete": "Delete",
    "admin.spaces.editTitle": "Edit space",
    "admin.spaces.provisionedDetail": "Provisioned detail",
    "admin.spaces.provisioningState": "Provisioning state",
    "admin.spaces.provisionedDirectoryItems": "Provisioned directory items",
    "admin.spaces.noProvisionedDetail": "No canonical provisioning detail is available for this space yet.",
    "admin.spaces.field.title": "Title",
    "admin.spaces.field.description": "Description",
    "admin.spaces.field.slug": "Slug",
    "admin.spaces.field.visibilityGroups": "Visibility groups",
    "admin.spaces.field.type": "Type",
    "admin.spaces.field.parent": "Parent",
    "admin.spaces.field.dashboardTemplate": "Dashboard template",
    "admin.spaces.field.layoutMode": "Layout mode",
    "admin.spaces.field.accessMode": "Visible before login",
    "admin.spaces.field.backgroundUrl": "Background URL",
    "admin.spaces.field.displayConfig": "Display config (JSON)",
    "admin.spaces.field.personalizationRules": "Personalization rules (JSON)",
    "admin.spaces.field.publicEntry": "Public entry",
    "admin.spaces.field.publicEntryTitle": "Public intro title",
    "admin.spaces.field.publicEntrySubtitle": "Public intro subtitle",
    "admin.spaces.field.publicEntryHelp": "Public help block",
    "admin.spaces.field.publicEntryContact": "Public contact block",
    "admin.spaces.option.parentNone": "None",
    "admin.spaces.option.templateAuto": "Auto by slug",
    "admin.spaces.option.type.audience": "Audience",
    "admin.spaces.option.type.shared": "Shared",
    "admin.spaces.option.type.system": "System",
    "admin.spaces.option.layout.grid": "Grid",
    "admin.spaces.option.layout.hero": "Hero",
    "admin.spaces.option.layout.list": "List",
    "admin.spaces.option.access.private": "Private",
    "admin.spaces.option.access.publicReadonly": "Public read-only",
    "admin.spaces.lockable": "Lockable",
    "admin.spaces.defaultPublicEntry": "Default public entry",
    "admin.spaces.placeholder.title": "Media",
    "admin.spaces.placeholder.description": "Films, music, and other things your household opens often.",
    "admin.spaces.placeholder.slug": "media",
    "admin.spaces.placeholder.visibilityGroups": "admin, user, guest",
    "admin.spaces.placeholder.backgroundUrl": "https://...",
    "admin.spaces.placeholder.publicEntryTitle": "Welcome to Atrium",
    "admin.spaces.placeholder.publicEntrySubtitle": "Local private-by-default workspace.",
    "admin.spaces.placeholder.publicEntryHelp": "Ask your operator for access.",
    "admin.spaces.placeholder.publicEntryContact": "ops@company.local",
    "admin.spaces.confirmDelete": "Delete space “{title}”?",
    "admin.spaces.confirmArchive": "Archive space “{title}”? It will disappear from the active Atrium until you restore it.",
    "admin.spaces.confirmRestore": "Restore space “{title}”? It will return to the active Atrium.",
    "admin.spaces.archivedDone": "Space archived",
    "admin.spaces.restoredDone": "Space restored",
    "admin.common.space": "Space",
    "admin.common.selectSpace": "Select space",
    "admin.common.email": "Email",
    "admin.common.role": "Role",
    "admin.common.selectRole": "Select role",
    "admin.common.validUntil": "Valid until",
    "admin.common.bulkImport": "Bulk import",
    "admin.common.title": "Title",
    "admin.common.description": "Description",
    "admin.common.body": "Body",
    "admin.common.priority": "Priority",
    "admin.common.pinned": "Pinned",
    "admin.common.unpinned": "Unpinned",
    "admin.common.audienceGroups": "Audience groups",
    "admin.common.type": "Type",
    "admin.common.url": "URL",
    "admin.common.iconUrl": "Icon URL",
    "admin.common.tags": "Tags",
    "admin.common.serviceType": "Service type",
    "admin.common.tier": "Tier",
    "admin.common.lifecycle": "Lifecycle",
    "admin.common.classification": "Classification",
    "admin.common.runbookUrl": "Runbook URL",
    "admin.common.accessPath": "Access path",
    "admin.common.dependsOn": "Depends on",
    "admin.common.ownersJson": "Owners (JSON)",
    "admin.common.linksJson": "Links (JSON)",
    "admin.common.endpointsJson": "Endpoints (JSON)",
    "admin.common.key": "Key",
    "admin.common.service": "Service",
    "admin.common.allSpaces": "All spaces",
    "admin.common.label": "Label",
    "admin.common.group": "Group",
    "admin.common.order": "Order",
    "admin.common.primaryUrl": "Primary URL",
    "admin.common.defaultEndpoint": "Default endpoint",
    "admin.common.allowedActions": "Allowed actions",
    "admin.common.visibleLinks": "Visible links",
    "admin.common.create": "Create",
    "admin.common.import": "Import",
    "admin.common.remove": "Remove",
    "admin.common.none": "none",
    "admin.common.noItems": "Nothing here yet.",
    "admin.common.option.normal": "Normal",
    "admin.common.option.high": "High",
    "admin.common.option.critical": "Critical",
    "admin.common.option.type.resource": "Resource",
    "admin.common.option.type.link": "Link",
    "admin.common.option.type.action": "Action",
    "admin.common.placeholder.email": "user@example.com",
    "admin.common.placeholder.segment": "kid-girl",
    "admin.common.placeholder.emails": "email1,email2,email3...",
    "admin.common.placeholder.title": "Title",
    "admin.common.placeholder.body": "Message...",
    "admin.common.placeholder.description": "Short description",
    "admin.common.placeholder.iconUrl": "printer or /icons/printer.svg",
    "admin.common.placeholder.url": "https://...",
    "admin.common.placeholder.tags": "tag1, tag2",
    "admin.common.placeholder.serviceType": "http/postgres/s3",
    "admin.common.placeholder.tier": "tier-1",
    "admin.common.placeholder.lifecycle": "active/deprecated",
    "admin.common.placeholder.classification": "internal/PII",
    "admin.common.placeholder.runbookUrl": "https://runbook...",
    "admin.common.placeholder.accessPath": "Access request / group",
    "admin.common.placeholder.dependsOn": "service-a, service-b",
    "admin.common.placeholder.ownersJson": "{\"team\":\"core\",\"primary\":\"a@b.com\"}",
    "admin.common.placeholder.linksJson": "{\"docs\":\"...\",\"repo\":\"...\"}",
    "admin.common.placeholder.endpointsJson": "[{\"type\":\"http\",\"url\":\"https://...\"}]",
    "admin.members.title": "Memberships",
    "admin.members.add": "Add member",
    "admin.members.none": "No members yet.",
    "admin.members.importDone": "Imported {count} members",
    "admin.members.until": "until {date}",
    "admin.members.selectSpaceError": "Select a space",
    "admin.content.directory": "Directory",
    "admin.content.provisionedDirectory": "Provisioned directory",
    "admin.content.provisionedDirectoryHint": "Read-only directory view from the canonical provisioning catalog for the selected space.",
    "admin.content.noneProvisionedDirectory": "No provisioned directory items for this space yet.",
    "admin.content.mutableDirectory": "Mutable directory",
    "admin.content.mutableDirectoryHint": "Editable directory surface for mutations that have not moved into provisioning yet.",
    "admin.content.noneDirectory": "No directory items yet.",
    "admin.content.createdDirectory": "Directory item created",
    "admin.content.updatedDirectory": "Directory updated",
    "admin.content.deletedDirectory": "Directory item deleted",
    "admin.content.confirmDeleteDirectory": "Delete directory item \"{title}\"?",
    "admin.dashboard.templates": "Dashboard templates",
    "admin.dashboard.blocksCount": "{count} blocks",
    "admin.dashboard.templateVersion": "Template version",
    "admin.dashboard.provisionedBlocksCount": "{count} provisioned blocks",
    "admin.dashboard.editorBlocksCount": "{count} editor draft blocks",
    "admin.dashboard.blockTypes": "Block types",
    "admin.dashboard.loadingProvisionedTemplate": "Loading canonical template detail...",
    "admin.dashboard.noProvisionedTemplate": "Canonical template detail is not available yet.",
    "admin.dashboard.loadingProvisionedDashboard": "Loading canonical dashboard snapshot...",
    "admin.dashboard.noProvisionedDashboard": "Canonical dashboard snapshot is not available yet.",
    "admin.dashboard.editBlocks": "Edit blocks",
    "admin.dashboard.editor": "Dashboard editor",
    "admin.dashboard.preview": "Preview",
    "admin.dashboard.blocks": "Blocks",
    "admin.segment": "Segment",
    "admin.segmentSaved": "Segment updated",
    "admin.reload": "Reload config",
    "admin.reloading": "Reloading...",
    "admin.reloadDone": "Config reloaded",
    "admin.reloadFailed": "Config reload failed",
    "app.saveDone": "Saved",
    "app.saveFailed": "Save failed",
    "space.picker.title": "Spaces",
    "space.picker.subtitle": "Switch your context",
    "space.picker.results": "Results",
    "space.picker.recents": "Recents",
    "space.picker.pinned": "Pinned",
    "space.picker.all": "All spaces",
    "space.picker.pin": "Pin",
    "space.lock": "Lock space",
    "dashboard.empty.title": "Dashboard not configured yet",
    "dashboard.empty.body": "The v1 baseline keeps orientation and curated entry points visible even before heavy customization.",
    "dashboard.calendarUpcoming.body": "The upcoming week summary is published through the dedicated calendar surface.",
    "dashboard.calendarUpcoming.missing": "Calendar surface is not published yet.",
    "dashboard.inventorySummary.body": "Inventory summary stays in Atrium, while drilldown opens through the dedicated inventory surface.",
    "dashboard.inventorySummary.missing": "Inventory surface is not published yet.",
    "dashboard.summary.visible": "Visible",
    "dashboard.summary.events": "Events",
    "dashboard.summary.reminders": "Reminders",
    "dashboard.summary.totalItems": "Items",
    "dashboard.summary.attention": "Attention",
    "resource.noPinned": "No pinned resources",
    "resource.noActivity": "No activity yet",
    "resource.copied": "Copied",
    "resource.copyFailed": "Copy failed",
    "resource.actionInvoked": "Action invoked",
    "resource.actionFailed": "Action failed",
    "resource.publicReadonly": "Public spaces are read-only",
    "resource.details.title": "Resource details",
    "resource.details.overview": "Overview",
    "resource.details.access": "Access",
    "resource.details.actions": "Actions",
    "resource.details.ownership": "Ownership",
    "resource.details.links": "Links",
    "resource.details.endpoints": "Endpoints",
    "resource.details.service": "Service",
    "resource.details.titleField": "Title",
    "resource.details.description": "Description",
    "resource.details.type": "Type",
    "resource.details.tier": "Tier",
    "resource.details.lifecycle": "Lifecycle",
    "resource.details.primaryLink": "Primary link",
    "resource.details.endpoint": "Endpoint",
    "resource.details.region": "Region",
    "resource.details.bucket": "Bucket",
    "resource.details.console": "Console",
    "resource.details.accessPath": "Access path",
    "resource.details.s3": "S3 details",
    "resource.details.openConsole": "Open console",
    "resource.details.copyS3": "Copy s3://",
    "resource.details.copyCli": "Copy CLI",
    "resource.details.noActions": "No actions configured.",
    "editor.addBlockTitle": "Add block",
    "editor.addBlockBody": "Choose a block type to add to the dashboard.",
    "editor.blockSettings": "Block settings",
    "editor.advanced": "Advanced layout",
    "editor.advancedHint": "Raw grid coordinates stay available when you need exact placement.",
    "editor.showAdvanced": "Show advanced",
    "editor.hideAdvanced": "Hide advanced",
    "editor.canonicalSnapshot": "Canonical provisioning snapshot",
    "editor.canonicalLoading": "Loading canonical dashboard snapshot...",
    "editor.canonicalUnavailable": "Canonical dashboard snapshot is not available yet.",
    "editor.canonicalBlocks": "Canonical blocks",
    "editor.editableBlocks": "Editable draft blocks",
    "editor.useCanonicalDraft": "Use canonical snapshot as draft",
    "editor.resetDraft": "Reset draft",
    "editor.compareHint": "This snapshot is canonical and read-only. The editable form on the right writes through the neutral dashboard mutation API.",
    "surface.kids.title": "Safe kids entry",
    "surface.kids.subtitle": "Only the allowed and easy-to-understand things should be here.",
    "surface.kids.safeTitle": "Bounded by default",
    "surface.kids.safeBody": "Kids see a smaller, calmer surface with fewer choices and no operator-only controls.",
    "surface.kids.allowedTitle": "Allowed now",
    "surface.kids.allowedBody": "These entries are prepared for safe access without extra navigation.",
    "surface.kids.helpTitle": "When something is unavailable",
    "surface.kids.helpBody": "Messages stay gentle and human-readable. Ask an adult or operator if something important is missing.",
    "surface.admin.title": "Operator control surface",
    "surface.admin.subtitle": "State, risk, and next steps come before the tool list.",
    "surface.admin.backupTitle": "Backup posture",
    "surface.admin.backupBody": "Backup entry points should stay visible from the first screen so restore does not begin from guesswork.",
    "surface.admin.updateTitle": "Update readiness",
    "surface.admin.updateBody": "Before making changes, confirm rollback readiness and the critical services that must survive the rollout.",
    "surface.admin.criticalTitle": "Critical signals",
    "surface.admin.criticalBody": "Problems should rise above ordinary links. If nothing is flagged, Atrium should say so calmly.",
    "surface.admin.recoveryTitle": "Recovery actions",
    "surface.admin.recoveryBody": "The operator needs a next step: backup storage, observability, identity surface, and restore-oriented guidance.",
    "surface.state.ready": "Ready",
    "surface.state.review": "Needs review",
    "surface.state.clear": "No critical alerts",
    "surface.state.attention": "Needs attention",
    "surface.state.guided": "Guided",
    "surface.action.openResource": "Open resource",
    "surface.action.openCalendar": "Open calendar",
    "surface.action.openInventory": "Open inventory",
    "surface.action.openAdmin": "Open admin panel",
    "block.type.resourcesPinned": "Pinned resources",
    "block.type.calendarUpcoming": "Upcoming calendar",
    "block.type.inventorySummary": "Inventory summary",
    "block.type.text": "Text",
    "resource.pinned.expand": "Show all",
    "resource.pinned.collapse": "Hide full list",
    "resource.group.products": "Active products",
    "resource.group.services": "Local services",
    "resource.group.external": "External",
    "resource.group.future": "Future",
    "language.title": "Language",
    "performance.title": "Performance",
    "performance.auto": "Auto",
    "performance.low": "Low",
    "performance.normal": "Normal",
    "role.switch": "Switch role",
    "role.actingAs": "Admin session • acting as {role}",
  },
  ru: {
    "app.title": "Atrium",
    "app.spaces": "Пространства",
    "app.switchContext": "Переключайте контекст",
    "app.searchSpaces": "Поиск пространств",
    "app.noSpaces": "Пространств пока нет.",
    "app.login": "Войти",
    "app.language": "Язык",
    "app.logout": "Выйти",
    "app.settings": "Настройки",
    "app.theme": "Тема",
    "app.themeDark": "Тёмная",
    "app.themeLight": "Светлая",
    "app.themeAuto": "Авто",
    "app.home": "Главная",
    "app.privacy": "Приватность",
    "app.adminPanel": "Панель администратора",
    "app.back": "Назад",
    "app.close": "Закрыть",
    "app.addBlock": "Добавить блок",
    "app.addBlockShort": "Добавить",
    "app.save": "Сохранить",
    "app.saveDashboard": "Сохранить дашборд",
    "app.cancel": "Отмена",
    "app.editLayout": "Редактировать раскладку",
    "app.exit": "Выйти",
    "app.details": "Детали",
    "app.keyboardShortcuts": "Горячие клавиши",
    "assistant.tabs.ariaLabel": "Разделы ассистента",
    "assistant.tabs.chat": "Чат",
    "assistant.tabs.capabilities": "Возможности",
    "assistant.tabs.routines": "Рутины",
    "assistant.tabs.artifacts": "Артефакты",
    "assistant.tabs.pages": "Страницы",
    "assistant.sidebar.expand": "Развернуть сайдбар",
    "assistant.sidebar.collapse": "Свернуть сайдбар",
    "assistant.sidebar.newChat": "Новый чат",
    "assistant.sidebar.searchPlaceholder": "Поиск по чатам",
    "assistant.sidebar.loadingChats": "Загружаем чаты…",
    "assistant.sidebar.emptyChats": "Здесь будут ваши чаты.",
    "assistant.sidebar.searchEmpty": "Ничего не найдено",
    "assistant.sidebar.trash": "Корзина",
    "assistant.sidebar.loading": "Загружаем…",
    "assistant.sidebar.trashEmpty": "Корзина пуста.",
    "assistant.sidebar.capabilitiesFiltersSoon": "Фильтры появятся в Wave 2.",
    "assistant.sidebar.routinesFiltersSoon": "Фильтры появятся в Wave 3.",
    "assistant.sidebar.resize": "Изменить ширину сайдбара",
    "assistant.sidebar.untitled": "Без названия",
    "assistant.sidebar.openMenu": "Открыть меню чата",
    "assistant.sidebar.rename": "Переименовать",
    "assistant.sidebar.delete": "Удалить",
    "assistant.sidebar.restore": "Восстановить",
    "assistant.sidebar.group.today": "Сегодня",
    "assistant.sidebar.group.yesterday": "Вчера",
    "assistant.sidebar.group.week": "7 дней",
    "assistant.sidebar.group.month": "30 дней",
    "assistant.sidebar.group.older": "Старше",
    "assistant.composer.disabled": "Assistant выключен",
    "assistant.composer.placeholder": "Сообщение… (Enter — отправить, Shift+Enter — перенос)",
    "assistant.composer.send": "Отправить сообщение",
    "assistant.composer.stop": "Остановить генерацию",
    "assistant.composer.modelMissing": "{id} (недоступна)",
    "assistant.composer.noModel": "Модель не выбрана",
    "assistant.composer.defaultForNew": "По умолчанию для новых чатов",
    "assistant.conversation.loading": "Загружаем чат…",
    "assistant.conversation.today": "Сегодня",
    "assistant.conversation.yesterday": "Вчера",
    "assistant.empty.subtitle": "Спроси что угодно или начни с подсказки.",
    "assistant.empty.providerNotice": "Модель настраивает оператор: это может быть сторонний провайдер со своими правилами обработки и retention.",
    "assistant.empty.reliabilityNotice": "ИИ может ошибаться. Не принимай ответы как проверенный факт без проверки.",
    "assistant.suggestion.explainCode": "Объясни код",
    "assistant.suggestion.generateIdea": "Сгенерируй идею",
    "assistant.suggestion.helpEmail": "Помоги с письмом",
    "assistant.suggestion.summarize": "Сделай резюме",
    "assistant.status.creating": "Создаем run…",
    "assistant.status.queued": "Запрос в очереди…",
    "assistant.status.running": "Модель начала обработку…",
    "assistant.status.receiving": "Модель отвечает…",
    "assistant.status.cancelling": "Останавливаем генерацию…",
    "assistant.status.reconnecting": "Восстанавливаем поток…",
    "assistant.latency.thinking": "Думает {time}",
    "assistant.latency.answering": "Отвечает {time} · думала {thinking}",
    "assistant.latency.completed": "Ответила за {total}",
    "assistant.latency.completedWithThinking": "Ответила за {total} · думала {thinking}",
    "assistant.undo.pending": "Удаление через 5 секунд",
    "assistant.undo.cancel": "Отменить",
    "assistant.dialog.renameTitle": "Новое название чата",
    "assistant.dialog.deleteConfirm": "Удалить чат «{title}»? Его можно восстановить из корзины.",
    "assistant.message.proposalOne": "Предлагаю запустить {name}",
    "assistant.message.proposalBatch": "Предлагаю запустить batch: {names}",
    "assistant.message.awaitingApproval": "ожидает подтверждения",
    "assistant.message.statusApproved": "подтверждено",
    "assistant.message.statusRejected": "отклонено",
    "assistant.message.statusCancelled": "отменено",
    "assistant.message.approve": "Запускать",
    "assistant.message.reject": "Отклонить",
    "assistant.message.surfacePatchSummary": "{pageKind} · изменений: {count}",
    "assistant.message.surfacePatchApply": "Применить к {pageKind}",
    "assistant.message.surfacePatchReject": "Отклонить",
    "assistant.message.surfacePatchApplied": "Применено",
    "assistant.message.surfacePatchRejected": "Отклонено",
    "assistant.message.surfacePatchOpen": "Открыть страницу",
    "assistant.message.surfacePatchHint": "Создаст новую версию страницы — потом можно открыть и доредактировать.",
    "assistant.message.surfacePatchOp.addBlock": "+ блок {block} в {region}",
    "assistant.message.surfacePatchOp.removeBlock": "− блок {blockRef}",
    "assistant.message.surfacePatchOp.setProps": "изменены свойства {blockRef}",
    "assistant.message.surfacePatchOp.moveBlock": "{blockRef}: {fromRegion} → {toRegion}",
    "assistant.message.surfacePatchOp.setLayout": "макет → {layout}",
    "assistant.message.changeLayout": "Изменить раскладку skill",
    "assistant.message.copy": "Скопировать сообщение",
    "assistant.message.copyCode": "Копировать",
    "assistant.message.copiedCode": "Скопировано",
    "assistant.message.regenerate": "Сгенерировать заново",
    "assistant.message.retry": "Повторить",
    "assistant.message.deletePair": "Удалить пару сообщений",
    "assistant.message.stopped": "Генерация остановлена.",
    "assistant.message.thinking": "Размышления",
    "assistant.step.skillProposal": "Подготовка {skill}",
    "assistant.step.skillRun": "Запуск {skill}",
    "assistant.step.unknown": "Шаг ассистента",
    "assistant.step.status.running": "выполняется",
    "assistant.step.status.completed": "готово",
    "assistant.step.status.failed": "ошибка",
    "assistant.step.status.unknown": "статус неизвестен",
    "assistant.layout.compact": "Compact",
    "assistant.layout.cards": "Cards",
    "assistant.capabilities.intro": "Что Void Assistant умеет делать — это код, поставляемый с релизом void. Skills нельзя редактировать или удалить из UI: карточка показывает, что произойдёт при запуске и как попросить ассистента об этом в чате.",
    "assistant.capabilities.loading": "Загружаем каталог…",
    "assistant.capabilities.empty": "Каталог пуст — skills ещё не shipped.",
    "assistant.capabilities.noResults": "Ничего не нашлось под текущие фильтры.",
    "assistant.capabilities.resetFilters": "Сбросить фильтры",
    "assistant.capabilities.filterSummary": "{count} skills в каталоге. Фильтры появятся, когда каталог станет разнообразнее.",
    "assistant.filters.all": "Все",
    "assistant.filters.stage": "Этап",
    "assistant.filters.stageValue": "Этап {value}",
    "assistant.filters.domain": "Домен",
    "assistant.filters.output": "Вывод",
    "assistant.filters.trustClass": "Класс доверия",
    "assistant.filters.status": "Статус",
    "assistant.filters.enabled": "Включено",
    "assistant.filters.paused": "На паузе",
    "assistant.filters.trigger": "Триггер",
    "assistant.filters.autonomy": "Автономность",
    "assistant.skill.trust.trusted_graph": "читает данные Void",
    "assistant.skill.trust.untrusted_web": "читает публичный веб",
    "assistant.skill.trust.trusted_user_input": "использует ваш ввод",
    "assistant.skill.trust.proposed_kadath": "готовит изменение в графе",
    "assistant.skill.trust.untrusted_external_mcp": "читает внешний сервис",
    "assistant.skill.trust.untrusted_sensor": "читает внешний сигнал",
    "assistant.skill.trust.unknown": "требует проверки источника",
    "assistant.skill.evalPassed": "Проверено в поставке",
    "assistant.skill.evalNeedsReview": "Требует проверки",
    "assistant.skill.version": "Навык · версия {version}",
    "assistant.skill.source": "Источник",
    "assistant.skill.result": "Результат",
    "assistant.skill.restrictions": "Ограничения",
    "assistant.skill.call": "Как вызвать",
    "assistant.skill.sayInChat": "Скажите в чате: «{phrase}».",
    "assistant.skill.launchExplain": "Кнопка ниже откроет готовую карточку подтверждения этого навыка.",
    "assistant.skill.details": "Технические детали",
    "assistant.skill.footer": "Запуск начнётся только после подтверждения в чате.",
    "assistant.skill.openInChat": "Открыть запуск в чате",
    "assistant.skill.openInChatTitle": "Откроет чат и подготовит карточку подтверждения. Сам навык стартует после подтверждения.",
    "assistant.skill.source.http": "читает публичные веб-источники",
    "assistant.skill.source.none": "не читает внешние источники",
    "assistant.skill.source.allowed": "читает разрешённые источники",
    "assistant.skill.result.digest": "создаёт дайджест в чате",
    "assistant.skill.result.none": "ничего не записывает",
    "assistant.skill.result.structured": "создаёт структурированный результат",
    "assistant.skill.restrictions.none": "запрещённых действий нет",
    "assistant.skill.invoke.digest_hackernews": "дай дайджест Hacker News",
    "assistant.skill.invoke.digest_github": "дай дайджест трендовых репозиториев GitHub",
    "assistant.skill.invoke.default": "запусти {name}",
    "assistant.template.enabled": "routine enabled",
    "assistant.template.notEnabled": "не включено",
    "assistant.template.view": "View routine",
    "assistant.template.enable": "Enable",
    "assistant.routines.title": "Routines",
    "assistant.routines.intro": "Это твои настроенные программы ассистента — ContractInstance per-owner. Чтобы создать новую, попроси в chat или выбери template из Capabilities.",
    "assistant.routines.newFromTemplate": "Из template…",
    "assistant.routines.loading": "Загружаем…",
    "assistant.routines.emptyTitle": "Пока ничего не настроено",
    "assistant.routines.emptyText": "Заведи routine через диалог в Chat или нажми «Из template…» наверху.",
    "assistant.routines.noResults": "Ничего не нашлось под текущие фильтры.",
    "assistant.routines.resetFilters": "Сбросить фильтры",
    "assistant.routine.pause": "Поставить routine на паузу",
    "assistant.routine.enable": "Включить routine",
    "assistant.routine.paused": "paused",
    "assistant.routine.lastRun": "last run: {value}",
    "assistant.routine.next": "next: {value}",
    "assistant.routine.never": "ещё не запускалось",
    "assistant.routine.justNow": "только что",
    "assistant.routine.hoursAgo": "{count}h ago",
    "assistant.routine.daysAgo": "{count}d ago",
    "assistant.routine.runs": "Runs",
    "assistant.routine.edit": "Edit",
    "assistant.routine.more": "More",
    "assistant.routine.drawer.create": "Новая routine",
    "assistant.routine.drawer.edit": "Edit routine",
    "assistant.routine.drawer.inspect": "Routine · inspect",
    "assistant.routine.drawer.untitled": "Без названия",
    "assistant.routine.drawer.displayName": "Display name",
    "assistant.routine.drawer.displayNamePlaceholder": "например: Weekly shopping run",
    "assistant.routine.drawer.skill": "Skill",
    "assistant.routine.drawer.skillNote": "Skill нельзя поменять на existing routine — это создаст новую, потому что skill_version_pin должен оставаться coherent с run history.",
    "assistant.routine.drawer.trigger": "Trigger",
    "assistant.routine.drawer.triggerPlaceholder": "например: sunday 10:00",
    "assistant.routine.drawer.autonomy": "Autonomy level",
    "assistant.routine.drawer.autonomyNote": "Bound сверху template'ом (operator-declared). Instance может только понизить уровень.",
    "assistant.routine.drawer.cancel": "Cancel",
    "assistant.routine.drawer.close": "Close",
    "assistant.routine.drawer.save": "Сохранить",
    "assistant.routine.drawer.saving": "Сохраняем…",
    "assistant.routine.drawer.createAction": "Создать routine",
    "assistant.block.unknown": "Неподдерживаемый блок: {type}",
    "assistant.metric.score": "баллов",
    "assistant.metric.descendants": "комментариев",
    "assistant.newspaper.lead": "Главное",
    "assistant.newspaper.secondary": "Материалы",
    "assistant.newspaper.rail": "Ещё",
    "assistant.report.back": "К Assistant",
    "assistant.report.title": "Выпуск газеты",
    "assistant.report.assembledAt": "Собрано {value}",
    "assistant.report.loading": "Загружаем выпуск...",
    "assistant.report.fetchFailed": "Не удалось загрузить выпуск.",
    "assistant.report.empty": "Выпуск недоступен.",
    "assistant.report.provenance": "Provenance выпуска",
    "assistant.report.schema": "Schema",
    "assistant.report.sources": "Source runs",
    "assistant.report.policy": "Editorial policy",
    "assistant.artifact.open": "Открыть",
    "artifact.back": "Назад",
    "artifact.loading": "Загружаем артефакт...",
    "artifact.empty": "Артефакт не найден.",
    "artifact.error.missing_id": "В URL отсутствует id артефакта.",
    "artifact.error.fetch_failed": "Не удалось загрузить артефакт.",
    "artifact.error.unsupported_schema": "Неподдерживаемая schema артефакта: {schema}",
    "artifact.newspaper.default_title": "Газета",
    "artifact.newspaper.total_count": "{count} материалов",
    "artifact.newspaper.sort.top_score": "Сортировка по баллам",
    "artifact.newspaper.sort.recent": "Сортировка по свежести",
    "artifact.list.title": "Артефакты",
    "artifact.list.empty": "Пока нет артефактов. Запусти скилл в чате чтобы создать первый.",
    "artifact.list.loading": "Загружаем артефакты...",
    "artifact.list.load_more": "Загрузить ещё",
    "artifact.list.fetch_failed": "Не удалось загрузить список артефактов.",
    "artifact.list.delete": "Удалить",
    "artifact.list.delete_confirm": "Удалить этот артефакт? Действие необратимо.",
    "artifact.list.delete_failed": "Не удалось удалить артефакт.",
    "pages.list.title": "Страницы",
    "pages.list.subtitle": "Встроенные страницы и те, что ты настроил под себя.",
    "pages.list.empty": "Пока нет страниц.",
    "pages.list.loading": "Загружаем страницы...",
    "pages.list.fetch_failed": "Не удалось загрузить список страниц.",
    "pages.list.open": "Открыть",
    "pages.list.source.shipped": "Встроенная",
    "pages.list.source.custom": "Своя",
    "pages.list.customized": "Изменена",
    "pages.list.customized_version": "Изменена · v{version}",
    "pages.list.updated_at": "Обновлено {date}",
    "artifact.bridge.title_fallback": "Артефакт скилла",
    "artifact.bridge.open_fullscreen": "Открыть на весь экран",
    "artifact.bridge.empty.default": "Артефакт ещё не доступен.",
    "artifact.bridge.empty.no_run": "Подходящий запуск скилла ещё не сделан — запусти скилл чтобы наполнить.",
    "artifact.bridge.empty.schema_mismatch": "У последнего запуска другая схема артефакта.",
    "artifact.bridge.empty.routine_pending": "Lookup по routine появится в M3.",
    "artifact.bridge.empty.invalid_query": "Некорректная конфигурация блока.",
    "surface.render.default_title": "Кастомная страница",
    "surface.render.back": "Назад",
    "surface.render.loading": "Загружаем страницу...",
    "surface.render.empty": "Для этой страницы ещё нет сохранённой версии. Сначала соберите её.",
    "surface.render.error": "Не удалось загрузить страницу.",
    "surface.render.unsupported_block": "Неподдерживаемый блок: {block}",
    "surface.metric.field.totalItems": "Всего позиций",
    "surface.metric.field.lowStockCount": "Заканчивается",
    "surface.metric.field.missingCount": "Отсутствует",
    "surface.metric.field.recentChangesCount": "Недавние изменения",
    "surface.table.empty": "Нет позиций для показа.",
    "surface.table.column.name": "Название",
    "surface.table.column.sku": "Артикул",
    "surface.table.column.location": "Расположение",
    "surface.table.column.quantity": "Количество",
    "surface.table.column.status": "Статус",
    "surface.table.column.updatedAt": "Обновлено",
    "surface.tree.empty": "Нет расположений для показа.",
    "surface.timeline.empty": "Нет недавних изменений.",
    "surface.low_stock.title": "Заканчивается",
    "surface.low_stock.empty": "Нечего пополнять.",
    "surface.filter.title": "Фильтры",
    "surface.filter.empty": "Фильтры не включены.",
    "surface.filter.option.status": "Статус",
    "surface.filter.option.location": "Расположение",
    "surface.filter.option.lowStockOnly": "Только заканчивающиеся",
    "surface.filter.option.search": "Поиск",
    "nav.artifacts": "Артефакты",
    "app.shortcutsNavigateTitle": "Навигация по пространствам",
    "app.shortcutsNavigateBody": "Перемещение между рабочими поверхностями",
    "app.shortcutsHelpTitle": "Помощь",
    "app.shortcutsHelpBody": "Показать окно с клавишами",
    "app.loading": "Загрузка",
    "app.noAccessSpaces": "Для роли {role} пока нет доступных пространств.",
    "app.noAccessTitle": "Для вашей роли пространства ещё не опубликованы.",
    "app.noAccessBody": "Atrium уже работает, но оператор пока не назначил для этой учётной записи ни одного общего или персонального пространства.",
    "app.noAccessRoleTitle": "Текущая роль",
    "app.noAccessHelpTitle": "Что делать дальше",
    "app.noAccessHelpBody": "Если доступ уже должен быть, свяжитесь с оператором или выйдите и войдите под другой учётной записью.",
    "app.noAccessTrustTitle": "Почему экран остаётся пустым",
    "auth.title": "Вход в Atrium",
    "auth.subtitle": "Вход доступен только после настройки аутентификации Atrium.",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.continue": "Продолжить",
    "auth.signingIn": "Входим...",
    "auth.devQuick": "Быстрый вход для разработки",
    "auth.signInAs": "Войти как {email}",
    "auth.sso": "Войти через SSO",
    "auth.ssoHint": "Продолжить через настроенный OIDC-провайдер.",
    "auth.returnHint": "После входа вернёмся на {next}.",
    "auth.unavailable": "Для этого Atrium вход сейчас не настроен.",
    "auth.unavailableHint": "OIDC не настроен, а локальный вход недоступен.",
    "auth.loginFailed": "Ошибка входа",
    "auth.logoutFailed": "Ошибка выхода",
    "auth.requiredTitle": "Требуется вход",
    "auth.requiredBody": "Войдите, чтобы открыть рабочее пространство.",
    "guest.title": "Ваш Atrium",
    "guest.body": "Это вход в ваше локальное пространство. После входа здесь будут ваши сервисы, страницы и места.",
    "guest.availableTitle": "Пока пусто",
    "guest.availableNone": "Открытые пространства ещё не добавлены.",
    "guest.trustNote": "Личные и приватные пространства показываются только после входа.",
    "guest.loginCta": "Войти",
    "guest.contactTitle": "Дальше",
    "guest.contactBody": "Войдите, чтобы увидеть свои пространства и доступные разделы.",
    "guest.valueTitle": "Что это",
    "guest.valueBody": "Atrium помогает держать всё важное в одном месте, а не в десятках отдельных ссылок.",
    "guest.controlTitle": "Под вашим контролем",
    "guest.controlBody": "Данные и доступ остаются на вашей стороне.",
    "guest.accessStepsTitle": "Как войти",
    "guest.accessStepsBody": "Войдите под своей учётной записью. После входа Atrium покажет доступные вам пространства.",
    "guest.publicShellTitle": "Публичные пространства",
    "guest.publicShellSubtitle": "Здесь видны только пространства с режимом public_readonly.",
    "spaces.welcomeTitle": "Добро пожаловать в Atrium",
    "spaces.welcomeBody": "Создайте своё первое пространство, чтобы начать работу.",
    "spaces.publicIntroTitle": "Публичный доступ",
    "spaces.publicIntroSubtitle": "Пространства только для чтения, доступные до входа.",
    "spaces.publicHelp": "Публичная информация и контакты настраиваются оператором.",
    "spaces.family": "Семья",
    "spaces.familyDesc": "Home, Kids, Admin",
    "spaces.openAdmin": "Открыть админку",
    "spaces.adminHint": "Админка открывает read-only операторский экран с реальными ресурсами и точками входа.",
    "admin.title.overview": "Администрирование",
    "admin.subtitle.overview": "Read-only операторский обзор, собранный из опубликованных admin-ресурсов.",
    "admin.title.spaces": "Пространства",
    "admin.subtitle.spaces": "Управление пространствами Atrium с сопоставлением редактируемого состояния и canonical provisioning read model.",
    "admin.title.members": "Участники",
    "admin.subtitle.members": "Memberships и назначение ролей пока остаются изменяемыми, но role semantics уже подпитываются canonical provisioning catalog.",
    "admin.title.content": "Контент",
    "admin.subtitle.content": "Provisioned directory reads уже показаны рядом с оставшимся нейтральным mutation surface.",
    "admin.title.dashboard": "Дашборд",
    "admin.subtitle.dashboard": "Редактирование дашборда ещё переходное, но admin shell уже работает с пространствами, читаемыми через provisioning artifact.",
    "admin.spaces.create": "Новое пространство",
    "admin.spaces.createAction": "Создать пространство",
    "admin.spaces.active": "Активные пространства",
    "admin.spaces.archived": "Архивированные пространства",
    "admin.spaces.edit": "Изменить",
    "admin.spaces.archive": "В архив",
    "admin.spaces.restore": "Восстановить",
    "admin.spaces.delete": "Удалить",
    "admin.spaces.editTitle": "Изменить пространство",
    "admin.spaces.provisionedDetail": "Provisioning detail",
    "admin.spaces.provisioningState": "Состояние provisioning",
    "admin.spaces.provisionedDirectoryItems": "Provisioned directory items",
    "admin.spaces.noProvisionedDetail": "Для этого пространства пока нет отдельного canonical provisioning detail.",
    "admin.spaces.field.title": "Название",
    "admin.spaces.field.description": "Описание",
    "admin.spaces.field.slug": "Slug",
    "admin.spaces.field.visibilityGroups": "Группы видимости",
    "admin.spaces.field.type": "Тип",
    "admin.spaces.field.parent": "Родитель",
    "admin.spaces.field.dashboardTemplate": "Шаблон дашборда",
    "admin.spaces.field.layoutMode": "Режим раскладки",
    "admin.spaces.field.accessMode": "Видно до входа",
    "admin.spaces.field.backgroundUrl": "Фоновый URL",
    "admin.spaces.field.displayConfig": "Display config (JSON)",
    "admin.spaces.field.personalizationRules": "Personalization rules (JSON)",
    "admin.spaces.field.publicEntry": "Публичный вход",
    "admin.spaces.field.publicEntryTitle": "Заголовок публичного входа",
    "admin.spaces.field.publicEntrySubtitle": "Подзаголовок публичного входа",
    "admin.spaces.field.publicEntryHelp": "Блок помощи",
    "admin.spaces.field.publicEntryContact": "Контактный блок",
    "admin.spaces.option.parentNone": "Нет",
    "admin.spaces.option.templateAuto": "Авто по slug",
    "admin.spaces.option.type.audience": "Аудитория",
    "admin.spaces.option.type.shared": "Общее",
    "admin.spaces.option.type.system": "Системное",
    "admin.spaces.option.layout.grid": "Сетка",
    "admin.spaces.option.layout.hero": "Hero",
    "admin.spaces.option.layout.list": "Список",
    "admin.spaces.option.access.private": "Приватное",
    "admin.spaces.option.access.publicReadonly": "Публичное только для чтения",
    "admin.spaces.lockable": "Можно блокировать",
    "admin.spaces.defaultPublicEntry": "Публичный вход по умолчанию",
    "admin.spaces.placeholder.title": "Медиа",
    "admin.spaces.placeholder.description": "Фильмы, музыка и другие вещи, которые семья часто открывает.",
    "admin.spaces.placeholder.slug": "media",
    "admin.spaces.placeholder.visibilityGroups": "admin, user, guest",
    "admin.spaces.placeholder.backgroundUrl": "https://...",
    "admin.spaces.placeholder.publicEntryTitle": "Добро пожаловать в Atrium",
    "admin.spaces.placeholder.publicEntrySubtitle": "Локальное приватное пространство по умолчанию.",
    "admin.spaces.placeholder.publicEntryHelp": "Запросите доступ у оператора.",
    "admin.spaces.placeholder.publicEntryContact": "ops@company.local",
    "admin.spaces.confirmDelete": "Удалить пространство «{title}»?",
    "admin.spaces.confirmArchive": "Архивировать пространство «{title}»? Оно исчезнет из активного Atrium, пока вы не вернёте его обратно.",
    "admin.spaces.confirmRestore": "Восстановить пространство «{title}»? Оно снова появится в активном Atrium.",
    "admin.spaces.archivedDone": "Пространство архивировано",
    "admin.spaces.restoredDone": "Пространство восстановлено",
    "admin.common.space": "Пространство",
    "admin.common.selectSpace": "Выберите пространство",
    "admin.common.email": "Email",
    "admin.common.role": "Роль",
    "admin.common.selectRole": "Выберите роль",
    "admin.common.validUntil": "Действует до",
    "admin.common.bulkImport": "Массовый импорт",
    "admin.common.title": "Название",
    "admin.common.description": "Описание",
    "admin.common.body": "Текст",
    "admin.common.priority": "Приоритет",
    "admin.common.pinned": "Закрепить",
    "admin.common.unpinned": "Не закреплено",
    "admin.common.audienceGroups": "Группы аудитории",
    "admin.common.type": "Тип",
    "admin.common.url": "URL",
    "admin.common.iconUrl": "URL иконки",
    "admin.common.tags": "Теги",
    "admin.common.serviceType": "Тип сервиса",
    "admin.common.tier": "Уровень",
    "admin.common.lifecycle": "Жизненный цикл",
    "admin.common.classification": "Классификация",
    "admin.common.runbookUrl": "URL runbook",
    "admin.common.accessPath": "Путь доступа",
    "admin.common.dependsOn": "Зависит от",
    "admin.common.ownersJson": "Owners (JSON)",
    "admin.common.linksJson": "Links (JSON)",
    "admin.common.endpointsJson": "Endpoints (JSON)",
    "admin.common.key": "Ключ",
    "admin.common.service": "Сервис",
    "admin.common.allSpaces": "Все пространства",
    "admin.common.label": "Подпись",
    "admin.common.group": "Группа",
    "admin.common.order": "Порядок",
    "admin.common.primaryUrl": "Основной URL",
    "admin.common.defaultEndpoint": "Endpoint по умолчанию",
    "admin.common.allowedActions": "Разрешённые действия",
    "admin.common.visibleLinks": "Видимые ссылки",
    "admin.common.create": "Создать",
    "admin.common.import": "Импортировать",
    "admin.common.remove": "Убрать",
    "admin.common.none": "нет",
    "admin.common.noItems": "Пока пусто.",
    "admin.common.option.normal": "Обычный",
    "admin.common.option.high": "Высокий",
    "admin.common.option.critical": "Критичный",
    "admin.common.option.type.resource": "Ресурс",
    "admin.common.option.type.link": "Ссылка",
    "admin.common.option.type.action": "Действие",
    "admin.common.placeholder.email": "user@example.com",
    "admin.common.placeholder.segment": "kid-girl",
    "admin.common.placeholder.emails": "email1,email2,email3...",
    "admin.common.placeholder.title": "Название",
    "admin.common.placeholder.body": "Сообщение...",
    "admin.common.placeholder.description": "Короткое описание",
    "admin.common.placeholder.iconUrl": "printer или /icons/printer.svg",
    "admin.common.placeholder.url": "https://...",
    "admin.common.placeholder.tags": "tag1, tag2",
    "admin.common.placeholder.serviceType": "http/postgres/s3",
    "admin.common.placeholder.tier": "tier-1",
    "admin.common.placeholder.lifecycle": "active/deprecated",
    "admin.common.placeholder.classification": "internal/PII",
    "admin.common.placeholder.runbookUrl": "https://runbook...",
    "admin.common.placeholder.accessPath": "Запрос доступа / группа",
    "admin.common.placeholder.dependsOn": "service-a, service-b",
    "admin.common.placeholder.ownersJson": "{\"team\":\"core\",\"primary\":\"a@b.com\"}",
    "admin.common.placeholder.linksJson": "{\"docs\":\"...\",\"repo\":\"...\"}",
    "admin.common.placeholder.endpointsJson": "[{\"type\":\"http\",\"url\":\"https://...\"}]",
    "admin.members.title": "Участники",
    "admin.members.add": "Добавить участника",
    "admin.members.none": "Участников пока нет.",
    "admin.members.importDone": "Импортировано участников: {count}",
    "admin.members.until": "до {date}",
    "admin.members.selectSpaceError": "Выберите пространство",
    "admin.content.directory": "Каталог",
    "admin.content.provisionedDirectory": "Provisioned каталог",
    "admin.content.provisionedDirectoryHint": "Read-only view из canonical provisioning catalog для выбранного пространства.",
    "admin.content.noneProvisionedDirectory": "Для этого пространства provisioned элементов пока нет.",
    "admin.content.mutableDirectory": "Mutable каталог",
    "admin.content.mutableDirectoryHint": "Редактируемая directory surface для мутаций, которые ещё не переехали в provisioning.",
    "admin.content.noneDirectory": "Элементов каталога пока нет.",
    "admin.content.createdDirectory": "Элемент каталога создан",
    "admin.content.updatedDirectory": "Каталог обновлён",
    "admin.content.deletedDirectory": "Элемент каталога удалён",
    "admin.content.confirmDeleteDirectory": "Удалить элемент каталога «{title}»?",
    "admin.dashboard.templates": "Шаблоны дашборда",
    "admin.dashboard.blocksCount": "Блоков: {count}",
    "admin.dashboard.templateVersion": "Версия шаблона",
    "admin.dashboard.provisionedBlocksCount": "Provisioned блоков: {count}",
    "admin.dashboard.editorBlocksCount": "Draft блоков в editor: {count}",
    "admin.dashboard.blockTypes": "Типы блоков",
    "admin.dashboard.loadingProvisionedTemplate": "Загружаем canonical detail шаблона...",
    "admin.dashboard.noProvisionedTemplate": "Canonical detail шаблона пока недоступен.",
    "admin.dashboard.loadingProvisionedDashboard": "Загружаем canonical dashboard snapshot...",
    "admin.dashboard.noProvisionedDashboard": "Canonical dashboard snapshot пока недоступен.",
    "admin.dashboard.editBlocks": "Изменить блоки",
    "admin.dashboard.editor": "Редактор дашборда",
    "admin.dashboard.preview": "Предпросмотр",
    "admin.dashboard.blocks": "Блоки",
    "admin.segment": "Сегмент",
    "admin.segmentSaved": "Сегмент обновлен",
    "admin.reload": "Перезагрузить конфиг",
    "admin.reloading": "Перезагрузка...",
    "admin.reloadDone": "Конфиг перезагружен",
    "admin.reloadFailed": "Не удалось перезагрузить конфиг",
    "app.saveDone": "Сохранено",
    "app.saveFailed": "Не удалось сохранить",
    "space.picker.title": "Пространства",
    "space.picker.subtitle": "Переключайте контекст",
    "space.picker.results": "Результаты",
    "space.picker.recents": "Недавние",
    "space.picker.pinned": "Закрепленные",
    "space.picker.all": "Все пространства",
    "space.picker.pin": "Закрепить",
    "space.lock": "Блокировка пространства",
    "dashboard.empty.title": "Дашборд пока не настроен",
    "dashboard.empty.body": "В baseline v1 сначала должны быть видны ориентация и curated entry points, а уже потом глубокая кастомизация.",
    "dashboard.calendarUpcoming.body": "Сводка по ближайшей неделе публикуется через отдельную calendar surface.",
    "dashboard.calendarUpcoming.missing": "Calendar surface ещё не опубликована.",
    "dashboard.inventorySummary.body": "Inventory summary остаётся внутри Atrium, а drilldown открывается через отдельную inventory surface.",
    "dashboard.inventorySummary.missing": "Inventory surface ещё не опубликована.",
    "dashboard.summary.visible": "Видно",
    "dashboard.summary.events": "События",
    "dashboard.summary.reminders": "Напоминания",
    "dashboard.summary.totalItems": "Позиции",
    "dashboard.summary.attention": "Внимание",
    "resource.noPinned": "Закрепленных ресурсов пока нет",
    "resource.noActivity": "Активности пока нет",
    "resource.copied": "Скопировано",
    "resource.copyFailed": "Не удалось скопировать",
    "resource.actionInvoked": "Действие запущено",
    "resource.actionFailed": "Не удалось выполнить действие",
    "resource.publicReadonly": "Публичные пространства доступны только для чтения",
    "resource.details.title": "Детали ресурса",
    "resource.details.overview": "Обзор",
    "resource.details.access": "Доступ",
    "resource.details.actions": "Действия",
    "resource.details.ownership": "Владение",
    "resource.details.links": "Ссылки",
    "resource.details.endpoints": "Эндпоинты",
    "resource.details.service": "Сервис",
    "resource.details.titleField": "Название",
    "resource.details.description": "Описание",
    "resource.details.type": "Тип",
    "resource.details.tier": "Тир",
    "resource.details.lifecycle": "Жизненный цикл",
    "resource.details.primaryLink": "Основная ссылка",
    "resource.details.endpoint": "Эндпоинт",
    "resource.details.region": "Регион",
    "resource.details.bucket": "Бакет",
    "resource.details.console": "Консоль",
    "resource.details.accessPath": "Путь доступа",
    "resource.details.s3": "S3 детали",
    "resource.details.openConsole": "Открыть консоль",
    "resource.details.copyS3": "Скопировать s3://",
    "resource.details.copyCli": "Скопировать CLI",
    "resource.details.noActions": "Действия пока не настроены.",
    "editor.addBlockTitle": "Добавить блок",
    "editor.addBlockBody": "Выберите тип блока, который нужно добавить в дашборд.",
    "editor.blockSettings": "Настройки блока",
    "editor.advanced": "Продвинутая раскладка",
    "editor.advancedHint": "Сырые координаты сетки остаются доступны, когда нужен точный контроль.",
    "editor.showAdvanced": "Показать расширенные настройки",
    "editor.hideAdvanced": "Скрыть расширенные настройки",
    "editor.canonicalSnapshot": "Canonical provisioning snapshot",
    "editor.canonicalLoading": "Загружаем canonical dashboard snapshot...",
    "editor.canonicalUnavailable": "Canonical dashboard snapshot пока недоступен.",
    "editor.canonicalBlocks": "Canonical блоки",
    "editor.editableBlocks": "Редактируемые draft блоки",
    "editor.useCanonicalDraft": "Использовать canonical snapshot как draft",
    "editor.resetDraft": "Сбросить draft",
    "editor.compareHint": "Этот snapshot читается из canonical provisioning и остаётся read-only. Редактируемая форма справа пишет через нейтральный dashboard mutation API.",
    "surface.kids.title": "Безопасный детский вход",
    "surface.kids.subtitle": "Здесь должны оставаться только разрешённые и понятные вещи.",
    "surface.kids.safeTitle": "Ограничено по умолчанию",
    "surface.kids.safeBody": "Дети видят более спокойную поверхность с меньшим выбором и без операторских элементов управления.",
    "surface.kids.allowedTitle": "Разрешено сейчас",
    "surface.kids.allowedBody": "Эти входы подготовлены для безопасного использования без лишней навигации.",
    "surface.kids.helpTitle": "Если что-то недоступно",
    "surface.kids.helpBody": "Сообщения должны оставаться мягкими и понятными. Если чего-то важного не хватает, нужен взрослый или оператор.",
    "surface.admin.title": "Операторская поверхность контроля",
    "surface.admin.subtitle": "Состояние, риск и следующий шаг важнее списка инструментов.",
    "surface.admin.backupTitle": "Состояние резервных копий",
    "surface.admin.backupBody": "Точка входа к резервным копиям должна быть видна с первого экрана, чтобы восстановление не начиналось с догадок.",
    "surface.admin.updateTitle": "Готовность к обновлению",
    "surface.admin.updateBody": "Перед изменениями проверьте готовность к откату и критичные сервисы, которые обязаны пережить обновление.",
    "surface.admin.criticalTitle": "Критичные сигналы",
    "surface.admin.criticalBody": "Проблемы должны подниматься выше обычных ссылок. Если ничего критичного нет, Atrium должен сказать это спокойно.",
    "surface.admin.recoveryTitle": "Действия для восстановления",
    "surface.admin.recoveryBody": "Оператору нужен следующий шаг: резервные копии, наблюдаемость, вход и понятный путь к восстановлению.",
    "surface.state.ready": "Готово",
    "surface.state.review": "Нужна проверка",
    "surface.state.clear": "Критичных сигналов нет",
    "surface.state.attention": "Нужно внимание",
    "surface.state.guided": "Есть следующий шаг",
    "surface.action.openResource": "Открыть ресурс",
    "surface.action.openCalendar": "Открыть календарь",
    "surface.action.openInventory": "Открыть инвентарь",
    "surface.action.openAdmin": "Открыть панель администратора",
    "block.type.resourcesPinned": "Закреплённые ресурсы",
    "block.type.calendarUpcoming": "Ближайший календарь",
    "block.type.inventorySummary": "Сводка inventory",
    "block.type.text": "Текст",
    "resource.pinned.expand": "Все ресурсы",
    "resource.pinned.collapse": "Скрыть полный список",
    "resource.group.products": "Активные продукты",
    "resource.group.services": "Локальные сервисы",
    "resource.group.external": "Внешние",
    "resource.group.future": "Future",
    "language.title": "Язык",
    "performance.title": "Производительность",
    "performance.auto": "Авто",
    "performance.low": "Низкая",
    "performance.normal": "Обычная",
    "role.switch": "Сменить роль",
    "role.actingAs": "Сессия администратора • роль {role}",
  }
};

export const BLOCK_TYPES = {
  resourcesPinned: "core.resources_pinned",
  calendarUpcoming: "calendar_upcoming",
  inventorySummary: "inventory_summary",
  text: "core.text"
};

export const BLOCK_TYPE_OPTIONS = [
  { value: BLOCK_TYPES.resourcesPinned, label: "Pinned resources" }
];

export const BLOCK_TYPE_CARDS = [
  {
    value: BLOCK_TYPES.resourcesPinned,
    label: "Pinned resources",
    description: "Quick access links and resources.",
    icon: Bookmark
  }
];
