import { Bookmark } from "lucide-vue-next";

export const HOTKEYS = {
  next: "D / →",
  prev: "A / ←",
  help: "?"
};

export const FALLBACK_LANG = "ru";
export const LANG_STORAGE_KEY = "atrium:lang";
export const ENABLE_V0_EDITOR = false;
export const ENABLE_V0_DEV_ADMIN_SEAMS = false;
export const ENABLE_V0_RESOURCE_DETAILS = false;

export const MESSAGES = {
  en: {
    "app.title": "Atrium",
    "app.spaces": "Spaces",
    "app.switchContext": "Switch your context",
    "app.searchSpaces": "Search spaces",
    "app.noSpaces": "No spaces yet.",
    "app.login": "Login",
    "app.logout": "Log out",
    "app.home": "Home",
    "app.privacy": "Privacy",
    "app.adminPanel": "Admin Panel",
    "app.back": "Back",
    "app.close": "Close",
    "app.addBlock": "Add block",
    "app.addBlockShort": "Add",
    "app.save": "Save",
    "app.saveDashboard": "Save dashboard",
    "app.cancel": "Cancel",
    "app.editLayout": "Edit layout",
    "app.exit": "Exit",
    "app.details": "Details",
    "app.keyboardShortcuts": "Keyboard Shortcuts",
    "app.shortcutsNavigateTitle": "Navigate spaces",
    "app.shortcutsNavigateBody": "Move between workspaces",
    "app.shortcutsHelpTitle": "Help",
    "app.shortcutsHelpBody": "Show shortcuts overlay",
    "app.loading": "Loading",
    "app.noAccessSpaces": "No spaces available for {role}.",
    "app.noAccessTitle": "No spaces have been published for your role yet.",
    "app.noAccessBody": "Atrium is active, but the operator has not assigned a shared or personal space for this account yet.",
    "app.noAccessRoleTitle": "Current role",
    "app.noAccessHelpTitle": "What to do next",
    "app.noAccessHelpBody": "If you should already have access, contact the operator or sign out and try another account.",
    "app.noAccessTrustTitle": "Why the screen stays empty",
    "auth.title": "Sign in to Atrium",
    "auth.subtitle": "Sign-in is available only when Atrium authentication is configured.",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.continue": "Continue",
    "auth.signingIn": "Signing in...",
    "auth.devQuick": "Dev quick login",
    "auth.signInAs": "Sign in as {email}",
    "auth.sso": "Sign in with SSO",
    "auth.ssoHint": "Continue through the configured OIDC provider.",
    "auth.unavailable": "Sign-in is not configured for this Atrium.",
    "auth.unavailableHint": "OIDC is not configured and local sign-in is unavailable.",
    "auth.loginFailed": "Login failed",
    "auth.logoutFailed": "Logout failed",
    "auth.requiredTitle": "Authentication Required",
    "auth.requiredBody": "Sign in to access the workspace.",
    "guest.title": "Your Atrium",
    "guest.body": "This is the entry to your local space. After sign-in, your services, pages, and places appear here.",
    "guest.availableTitle": "Nothing public yet",
    "guest.availableNone": "Open spaces have not been added yet.",
    "guest.trustNote": "Personal and private spaces are shown only after sign-in.",
    "guest.loginCta": "Sign in",
    "guest.contactTitle": "Next",
    "guest.contactBody": "Sign in to see your spaces and available sections.",
    "guest.valueTitle": "What it is",
    "guest.valueBody": "Atrium keeps the important things in one place instead of scattering them across separate links.",
    "guest.controlTitle": "Under your control",
    "guest.controlBody": "Data and access stay on your side.",
    "guest.accessStepsTitle": "How to sign in",
    "guest.accessStepsBody": "Sign in with your account to see the spaces available to you.",
    "guest.publicShellTitle": "Public spaces",
    "guest.publicShellSubtitle": "Only the spaces marked public_readonly are visible here.",
    "spaces.welcomeTitle": "Welcome to Atrium",
    "spaces.welcomeBody": "Create your first space to get started.",
    "spaces.publicIntroTitle": "Public access",
    "spaces.publicIntroSubtitle": "Read-only spaces available before sign-in.",
    "spaces.publicHelp": "Public info and contact details set by the operator.",
    "spaces.family": "Family",
    "spaces.familyDesc": "Home, Kids, Admin",
    "spaces.openAdmin": "Open admin",
    "spaces.adminHint": "Admin opens a read-only operator surface with real resources and entry points.",
    "admin.title.overview": "Admin",
    "admin.subtitle.overview": "Read-only operator overview built from the published admin resources.",
    "admin.spaces.create": "New space",
    "admin.spaces.createAction": "Create space",
    "admin.spaces.active": "Active spaces",
    "admin.spaces.archived": "Archived spaces",
    "admin.spaces.edit": "Edit",
    "admin.spaces.archive": "Archive",
    "admin.spaces.restore": "Restore",
    "admin.spaces.delete": "Delete",
    "admin.spaces.editTitle": "Edit space",
    "admin.spaces.field.title": "Title",
    "admin.spaces.field.description": "Description",
    "admin.spaces.field.slug": "Slug",
    "admin.spaces.field.visibilityGroups": "Visibility groups",
    "admin.spaces.field.type": "Type",
    "admin.spaces.field.parent": "Parent",
    "admin.spaces.field.dashboardTemplate": "Dashboard template",
    "admin.spaces.field.layoutMode": "Layout mode",
    "admin.spaces.field.accessMode": "Visible before login",
    "admin.spaces.field.backgroundUrl": "Background URL",
    "admin.spaces.field.displayConfig": "Display config (JSON)",
    "admin.spaces.field.personalizationRules": "Personalization rules (JSON)",
    "admin.spaces.field.publicEntry": "Public entry",
    "admin.spaces.field.publicEntryTitle": "Public intro title",
    "admin.spaces.field.publicEntrySubtitle": "Public intro subtitle",
    "admin.spaces.field.publicEntryHelp": "Public help block",
    "admin.spaces.field.publicEntryContact": "Public contact block",
    "admin.spaces.option.parentNone": "None",
    "admin.spaces.option.templateAuto": "Auto by slug",
    "admin.spaces.option.type.audience": "Audience",
    "admin.spaces.option.type.shared": "Shared",
    "admin.spaces.option.type.system": "System",
    "admin.spaces.option.layout.grid": "Grid",
    "admin.spaces.option.layout.hero": "Hero",
    "admin.spaces.option.layout.list": "List",
    "admin.spaces.option.access.private": "Private",
    "admin.spaces.option.access.publicReadonly": "Public read-only",
    "admin.spaces.lockable": "Lockable",
    "admin.spaces.defaultPublicEntry": "Default public entry",
    "admin.spaces.placeholder.title": "Media",
    "admin.spaces.placeholder.description": "Films, music, and other things your household opens often.",
    "admin.spaces.placeholder.slug": "media",
    "admin.spaces.placeholder.visibilityGroups": "admin, user, guest",
    "admin.spaces.placeholder.backgroundUrl": "https://...",
    "admin.spaces.placeholder.publicEntryTitle": "Welcome to Atrium",
    "admin.spaces.placeholder.publicEntrySubtitle": "Local private-by-default workspace.",
    "admin.spaces.placeholder.publicEntryHelp": "Ask your operator for access.",
    "admin.spaces.placeholder.publicEntryContact": "ops@company.local",
    "admin.spaces.confirmDelete": "Delete space “{title}”?",
    "admin.spaces.confirmArchive": "Archive space “{title}”? It will disappear from the active Atrium until you restore it.",
    "admin.spaces.confirmRestore": "Restore space “{title}”? It will return to the active Atrium.",
    "admin.spaces.archivedDone": "Space archived",
    "admin.spaces.restoredDone": "Space restored",
    "admin.common.space": "Space",
    "admin.common.selectSpace": "Select space",
    "admin.common.email": "Email",
    "admin.common.role": "Role",
    "admin.common.selectRole": "Select role",
    "admin.common.validUntil": "Valid until",
    "admin.common.bulkImport": "Bulk import",
    "admin.common.title": "Title",
    "admin.common.description": "Description",
    "admin.common.body": "Body",
    "admin.common.priority": "Priority",
    "admin.common.pinned": "Pinned",
    "admin.common.audienceGroups": "Audience groups",
    "admin.common.type": "Type",
    "admin.common.url": "URL",
    "admin.common.iconUrl": "Icon URL",
    "admin.common.tags": "Tags",
    "admin.common.serviceType": "Service type",
    "admin.common.tier": "Tier",
    "admin.common.lifecycle": "Lifecycle",
    "admin.common.classification": "Classification",
    "admin.common.runbookUrl": "Runbook URL",
    "admin.common.accessPath": "Access path",
    "admin.common.dependsOn": "Depends on",
    "admin.common.ownersJson": "Owners (JSON)",
    "admin.common.linksJson": "Links (JSON)",
    "admin.common.endpointsJson": "Endpoints (JSON)",
    "admin.common.key": "Key",
    "admin.common.service": "Service",
    "admin.common.allSpaces": "All spaces",
    "admin.common.label": "Label",
    "admin.common.group": "Group",
    "admin.common.order": "Order",
    "admin.common.primaryUrl": "Primary URL",
    "admin.common.defaultEndpoint": "Default endpoint",
    "admin.common.allowedActions": "Allowed actions",
    "admin.common.visibleLinks": "Visible links",
    "admin.common.create": "Create",
    "admin.common.import": "Import",
    "admin.common.remove": "Remove",
    "admin.common.noItems": "Nothing here yet.",
    "admin.common.option.normal": "Normal",
    "admin.common.option.high": "High",
    "admin.common.option.critical": "Critical",
    "admin.common.option.type.resource": "Resource",
    "admin.common.option.type.link": "Link",
    "admin.common.option.type.action": "Action",
    "admin.common.placeholder.email": "user@example.com",
    "admin.common.placeholder.segment": "kid-girl",
    "admin.common.placeholder.emails": "email1,email2,email3...",
    "admin.common.placeholder.title": "Title",
    "admin.common.placeholder.body": "Message...",
    "admin.common.placeholder.description": "Short description",
    "admin.common.placeholder.iconUrl": "printer or /icons/printer.svg",
    "admin.common.placeholder.url": "https://...",
    "admin.common.placeholder.tags": "tag1, tag2",
    "admin.common.placeholder.serviceType": "http/postgres/s3",
    "admin.common.placeholder.tier": "tier-1",
    "admin.common.placeholder.lifecycle": "active/deprecated",
    "admin.common.placeholder.classification": "internal/PII",
    "admin.common.placeholder.runbookUrl": "https://runbook...",
    "admin.common.placeholder.accessPath": "Access request / group",
    "admin.common.placeholder.dependsOn": "service-a, service-b",
    "admin.common.placeholder.ownersJson": "{\"team\":\"core\",\"primary\":\"a@b.com\"}",
    "admin.common.placeholder.linksJson": "{\"docs\":\"...\",\"repo\":\"...\"}",
    "admin.common.placeholder.endpointsJson": "[{\"type\":\"http\",\"url\":\"https://...\"}]",
    "admin.members.title": "Memberships",
    "admin.members.add": "Add member",
    "admin.members.none": "No members yet.",
    "admin.members.importDone": "Imported {count} members",
    "admin.members.until": "until {date}",
    "admin.members.selectSpaceError": "Select a space",
    "admin.content.directory": "Directory",
    "admin.content.noneDirectory": "No directory items yet.",
    "admin.content.createdDirectory": "Directory item created",
    "admin.content.updatedDirectory": "Directory updated",
    "admin.content.deletedDirectory": "Directory item deleted",
    "admin.content.confirmDeleteDirectory": "Delete directory item \"{title}\"?",
    "admin.dashboard.templates": "Dashboard templates",
    "admin.dashboard.blocksCount": "{count} blocks",
    "admin.dashboard.editBlocks": "Edit blocks",
    "admin.dashboard.editor": "Dashboard editor",
    "admin.dashboard.preview": "Preview",
    "admin.dashboard.blocks": "Blocks",
    "admin.segment": "Segment",
    "admin.segmentSaved": "Segment updated",
    "admin.reload": "Reload config",
    "admin.reloading": "Reloading...",
    "admin.reloadDone": "Config reloaded",
    "admin.reloadFailed": "Config reload failed",
    "app.saveDone": "Saved",
    "app.saveFailed": "Save failed",
    "space.picker.title": "Spaces",
    "space.picker.subtitle": "Switch your context",
    "space.picker.results": "Results",
    "space.picker.recents": "Recents",
    "space.picker.pinned": "Pinned",
    "space.picker.all": "All spaces",
    "space.picker.pin": "Pin",
    "space.lock": "Lock space",
    "dashboard.empty.title": "Dashboard not configured yet",
    "dashboard.empty.body": "The v1 baseline keeps orientation and curated entry points visible even before heavy customization.",
    "resource.noPinned": "No pinned resources",
    "resource.noActivity": "No activity yet",
    "resource.copied": "Copied",
    "resource.copyFailed": "Copy failed",
    "resource.actionInvoked": "Action invoked",
    "resource.actionFailed": "Action failed",
    "resource.publicReadonly": "Public spaces are read-only",
    "resource.details.title": "Resource details",
    "resource.details.overview": "Overview",
    "resource.details.access": "Access",
    "resource.details.actions": "Actions",
    "resource.details.ownership": "Ownership",
    "resource.details.links": "Links",
    "resource.details.endpoints": "Endpoints",
    "resource.details.service": "Service",
    "resource.details.titleField": "Title",
    "resource.details.description": "Description",
    "resource.details.type": "Type",
    "resource.details.tier": "Tier",
    "resource.details.lifecycle": "Lifecycle",
    "resource.details.primaryLink": "Primary link",
    "resource.details.endpoint": "Endpoint",
    "resource.details.region": "Region",
    "resource.details.bucket": "Bucket",
    "resource.details.console": "Console",
    "resource.details.accessPath": "Access path",
    "resource.details.s3": "S3 details",
    "resource.details.openConsole": "Open console",
    "resource.details.copyS3": "Copy s3://",
    "resource.details.copyCli": "Copy CLI",
    "resource.details.noActions": "No actions configured.",
    "editor.addBlockTitle": "Add block",
    "editor.addBlockBody": "Choose a block type to add to the dashboard.",
    "editor.blockSettings": "Block settings",
    "editor.advanced": "Advanced layout",
    "editor.advancedHint": "Raw grid coordinates stay available when you need exact placement.",
    "editor.showAdvanced": "Show advanced",
    "editor.hideAdvanced": "Hide advanced",
    "surface.kids.title": "Safe kids entry",
    "surface.kids.subtitle": "Only the allowed and easy-to-understand things should be here.",
    "surface.kids.safeTitle": "Bounded by default",
    "surface.kids.safeBody": "Kids see a smaller, calmer surface with fewer choices and no operator-only controls.",
    "surface.kids.allowedTitle": "Allowed now",
    "surface.kids.allowedBody": "These entries are prepared for safe access without extra navigation.",
    "surface.kids.helpTitle": "When something is unavailable",
    "surface.kids.helpBody": "Messages stay gentle and human-readable. Ask an adult or operator if something important is missing.",
    "surface.admin.title": "Operator control surface",
    "surface.admin.subtitle": "State, risk, and next steps come before the tool list.",
    "surface.admin.backupTitle": "Backup posture",
    "surface.admin.backupBody": "Backup entry points should stay visible from the first screen so restore does not begin from guesswork.",
    "surface.admin.updateTitle": "Update readiness",
    "surface.admin.updateBody": "Before making changes, confirm rollback readiness and the critical services that must survive the rollout.",
    "surface.admin.criticalTitle": "Critical signals",
    "surface.admin.criticalBody": "Problems should rise above ordinary links. If nothing is flagged, Atrium should say so calmly.",
    "surface.admin.recoveryTitle": "Recovery actions",
    "surface.admin.recoveryBody": "The operator needs a next step: backup storage, observability, identity surface, and restore-oriented guidance.",
    "surface.shopping.title": "Shopping snapshot",
    "surface.shopping.subtitle": "Need to buy, current run, and recently closed should stay visible inside Atrium.",
    "surface.shopping.loadingTitle": "Loading shopping state",
    "surface.shopping.loadingBody": "Atrium is reading the current shopping snapshot.",
    "surface.shopping.errorBody": "Shopping summary is temporarily unavailable. Open the detail view for diagnostics.",
    "surface.shopping.needsTitle": "Need to buy",
    "surface.shopping.needsValue": "{count} active needs",
    "surface.shopping.emptyNeedsTitle": "No active needs",
    "surface.shopping.emptyNeedsBody": "No active purchase intents yet.",
    "surface.shopping.runTitle": "Current run",
    "surface.shopping.runValue": "{count} items · {actionable} actionable",
    "surface.shopping.emptyRunTitle": "No active run",
    "surface.shopping.emptyRunBody": "Nothing is in the current shopping batch yet. A new run starts automatically when an item is queued.",
    "surface.shopping.closedTitle": "Recently closed",
    "surface.shopping.closedValue": "{count} closed recently",
    "surface.shopping.emptyClosedTitle": "Nothing closed recently",
    "surface.shopping.emptyClosedBody": "Only purchased and dismissed items show here. Deferred leftovers stay in run history.",
    "surface.state.ready": "Ready",
    "surface.state.review": "Needs review",
    "surface.state.clear": "No critical alerts",
    "surface.state.attention": "Needs attention",
    "surface.state.guided": "Guided",
    "surface.action.openResource": "Open resource",
    "surface.action.openAdmin": "Open admin panel",
    "surface.action.openShopping": "Open shopping",
    "surface.action.refreshShopping": "Refresh",
    "surface.action.queueShoppingNeed": "Queue item",
    "surface.action.closeShoppingRun": "Close run and defer rest",
    "block.type.resourcesPinned": "Pinned resources",
    "block.type.text": "Text",
    "language.title": "Language",
    "performance.title": "Performance",
    "performance.auto": "Auto",
    "performance.low": "Low",
    "performance.normal": "Normal",
    "role.switch": "Switch role",
    "role.actingAs": "Admin session • acting as {role}"
  },
  ru: {
    "app.title": "Atrium",
    "app.spaces": "Пространства",
    "app.switchContext": "Переключайте контекст",
    "app.searchSpaces": "Поиск пространств",
    "app.noSpaces": "Пространств пока нет.",
    "app.login": "Войти",
    "app.logout": "Выйти",
    "app.home": "Главная",
    "app.privacy": "Приватность",
    "app.adminPanel": "Панель администратора",
    "app.back": "Назад",
    "app.close": "Закрыть",
    "app.addBlock": "Добавить блок",
    "app.addBlockShort": "Добавить",
    "app.save": "Сохранить",
    "app.saveDashboard": "Сохранить дашборд",
    "app.cancel": "Отмена",
    "app.editLayout": "Редактировать раскладку",
    "app.exit": "Выйти",
    "app.details": "Детали",
    "app.keyboardShortcuts": "Горячие клавиши",
    "app.shortcutsNavigateTitle": "Навигация по пространствам",
    "app.shortcutsNavigateBody": "Перемещение между рабочими поверхностями",
    "app.shortcutsHelpTitle": "Помощь",
    "app.shortcutsHelpBody": "Показать окно с клавишами",
    "app.loading": "Загрузка",
    "app.noAccessSpaces": "Для роли {role} пока нет доступных пространств.",
    "app.noAccessTitle": "Для вашей роли пространства ещё не опубликованы.",
    "app.noAccessBody": "Atrium уже работает, но оператор пока не назначил для этой учётной записи ни одного общего или персонального пространства.",
    "app.noAccessRoleTitle": "Текущая роль",
    "app.noAccessHelpTitle": "Что делать дальше",
    "app.noAccessHelpBody": "Если доступ уже должен быть, свяжитесь с оператором или выйдите и войдите под другой учётной записью.",
    "app.noAccessTrustTitle": "Почему экран остаётся пустым",
    "auth.title": "Вход в Atrium",
    "auth.subtitle": "Вход доступен только после настройки аутентификации Atrium.",
    "auth.email": "Email",
    "auth.password": "Пароль",
    "auth.continue": "Продолжить",
    "auth.signingIn": "Входим...",
    "auth.devQuick": "Быстрый вход для разработки",
    "auth.signInAs": "Войти как {email}",
    "auth.sso": "Войти через SSO",
    "auth.ssoHint": "Продолжить через настроенный OIDC-провайдер.",
    "auth.unavailable": "Для этого Atrium вход сейчас не настроен.",
    "auth.unavailableHint": "OIDC не настроен, а локальный вход недоступен.",
    "auth.loginFailed": "Ошибка входа",
    "auth.logoutFailed": "Ошибка выхода",
    "auth.requiredTitle": "Требуется вход",
    "auth.requiredBody": "Войдите, чтобы открыть рабочее пространство.",
    "guest.title": "Ваш Atrium",
    "guest.body": "Это вход в ваше локальное пространство. После входа здесь будут ваши сервисы, страницы и места.",
    "guest.availableTitle": "Пока пусто",
    "guest.availableNone": "Открытые пространства ещё не добавлены.",
    "guest.trustNote": "Личные и приватные пространства показываются только после входа.",
    "guest.loginCta": "Войти",
    "guest.contactTitle": "Дальше",
    "guest.contactBody": "Войдите, чтобы увидеть свои пространства и доступные разделы.",
    "guest.valueTitle": "Что это",
    "guest.valueBody": "Atrium помогает держать всё важное в одном месте, а не в десятках отдельных ссылок.",
    "guest.controlTitle": "Под вашим контролем",
    "guest.controlBody": "Данные и доступ остаются на вашей стороне.",
    "guest.accessStepsTitle": "Как войти",
    "guest.accessStepsBody": "Войдите под своей учётной записью. После входа Atrium покажет доступные вам пространства.",
    "guest.publicShellTitle": "Публичные пространства",
    "guest.publicShellSubtitle": "Здесь видны только пространства с режимом public_readonly.",
    "spaces.welcomeTitle": "Добро пожаловать в Atrium",
    "spaces.welcomeBody": "Создайте своё первое пространство, чтобы начать работу.",
    "spaces.publicIntroTitle": "Публичный доступ",
    "spaces.publicIntroSubtitle": "Пространства только для чтения, доступные до входа.",
    "spaces.publicHelp": "Публичная информация и контакты настраиваются оператором.",
    "spaces.family": "Семья",
    "spaces.familyDesc": "Home, Kids, Admin",
    "spaces.openAdmin": "Открыть админку",
    "spaces.adminHint": "Админка открывает read-only операторский экран с реальными ресурсами и точками входа.",
    "admin.title.overview": "Администрирование",
    "admin.subtitle.overview": "Read-only операторский обзор, собранный из опубликованных admin-ресурсов.",
    "admin.spaces.create": "Новое пространство",
    "admin.spaces.createAction": "Создать пространство",
    "admin.spaces.active": "Активные пространства",
    "admin.spaces.archived": "Архивированные пространства",
    "admin.spaces.edit": "Изменить",
    "admin.spaces.archive": "В архив",
    "admin.spaces.restore": "Восстановить",
    "admin.spaces.delete": "Удалить",
    "admin.spaces.editTitle": "Изменить пространство",
    "admin.spaces.field.title": "Название",
    "admin.spaces.field.description": "Описание",
    "admin.spaces.field.slug": "Slug",
    "admin.spaces.field.visibilityGroups": "Группы видимости",
    "admin.spaces.field.type": "Тип",
    "admin.spaces.field.parent": "Родитель",
    "admin.spaces.field.dashboardTemplate": "Шаблон дашборда",
    "admin.spaces.field.layoutMode": "Режим раскладки",
    "admin.spaces.field.accessMode": "Видно до входа",
    "admin.spaces.field.backgroundUrl": "Фоновый URL",
    "admin.spaces.field.displayConfig": "Display config (JSON)",
    "admin.spaces.field.personalizationRules": "Personalization rules (JSON)",
    "admin.spaces.field.publicEntry": "Публичный вход",
    "admin.spaces.field.publicEntryTitle": "Заголовок публичного входа",
    "admin.spaces.field.publicEntrySubtitle": "Подзаголовок публичного входа",
    "admin.spaces.field.publicEntryHelp": "Блок помощи",
    "admin.spaces.field.publicEntryContact": "Контактный блок",
    "admin.spaces.option.parentNone": "Нет",
    "admin.spaces.option.templateAuto": "Авто по slug",
    "admin.spaces.option.type.audience": "Аудитория",
    "admin.spaces.option.type.shared": "Общее",
    "admin.spaces.option.type.system": "Системное",
    "admin.spaces.option.layout.grid": "Сетка",
    "admin.spaces.option.layout.hero": "Hero",
    "admin.spaces.option.layout.list": "Список",
    "admin.spaces.option.access.private": "Приватное",
    "admin.spaces.option.access.publicReadonly": "Публичное только для чтения",
    "admin.spaces.lockable": "Можно блокировать",
    "admin.spaces.defaultPublicEntry": "Публичный вход по умолчанию",
    "admin.spaces.placeholder.title": "Медиа",
    "admin.spaces.placeholder.description": "Фильмы, музыка и другие вещи, которые семья часто открывает.",
    "admin.spaces.placeholder.slug": "media",
    "admin.spaces.placeholder.visibilityGroups": "admin, user, guest",
    "admin.spaces.placeholder.backgroundUrl": "https://...",
    "admin.spaces.placeholder.publicEntryTitle": "Добро пожаловать в Atrium",
    "admin.spaces.placeholder.publicEntrySubtitle": "Локальное приватное пространство по умолчанию.",
    "admin.spaces.placeholder.publicEntryHelp": "Запросите доступ у оператора.",
    "admin.spaces.placeholder.publicEntryContact": "ops@company.local",
    "admin.spaces.confirmDelete": "Удалить пространство «{title}»?",
    "admin.spaces.confirmArchive": "Архивировать пространство «{title}»? Оно исчезнет из активного Atrium, пока вы не вернёте его обратно.",
    "admin.spaces.confirmRestore": "Восстановить пространство «{title}»? Оно снова появится в активном Atrium.",
    "admin.spaces.archivedDone": "Пространство архивировано",
    "admin.spaces.restoredDone": "Пространство восстановлено",
    "admin.common.space": "Пространство",
    "admin.common.selectSpace": "Выберите пространство",
    "admin.common.email": "Email",
    "admin.common.role": "Роль",
    "admin.common.selectRole": "Выберите роль",
    "admin.common.validUntil": "Действует до",
    "admin.common.bulkImport": "Массовый импорт",
    "admin.common.title": "Название",
    "admin.common.description": "Описание",
    "admin.common.body": "Текст",
    "admin.common.priority": "Приоритет",
    "admin.common.pinned": "Закрепить",
    "admin.common.audienceGroups": "Группы аудитории",
    "admin.common.type": "Тип",
    "admin.common.url": "URL",
    "admin.common.iconUrl": "URL иконки",
    "admin.common.tags": "Теги",
    "admin.common.serviceType": "Тип сервиса",
    "admin.common.tier": "Уровень",
    "admin.common.lifecycle": "Жизненный цикл",
    "admin.common.classification": "Классификация",
    "admin.common.runbookUrl": "URL runbook",
    "admin.common.accessPath": "Путь доступа",
    "admin.common.dependsOn": "Зависит от",
    "admin.common.ownersJson": "Owners (JSON)",
    "admin.common.linksJson": "Links (JSON)",
    "admin.common.endpointsJson": "Endpoints (JSON)",
    "admin.common.key": "Ключ",
    "admin.common.service": "Сервис",
    "admin.common.allSpaces": "Все пространства",
    "admin.common.label": "Подпись",
    "admin.common.group": "Группа",
    "admin.common.order": "Порядок",
    "admin.common.primaryUrl": "Основной URL",
    "admin.common.defaultEndpoint": "Endpoint по умолчанию",
    "admin.common.allowedActions": "Разрешённые действия",
    "admin.common.visibleLinks": "Видимые ссылки",
    "admin.common.create": "Создать",
    "admin.common.import": "Импортировать",
    "admin.common.remove": "Убрать",
    "admin.common.noItems": "Пока пусто.",
    "admin.common.option.normal": "Обычный",
    "admin.common.option.high": "Высокий",
    "admin.common.option.critical": "Критичный",
    "admin.common.option.type.resource": "Ресурс",
    "admin.common.option.type.link": "Ссылка",
    "admin.common.option.type.action": "Действие",
    "admin.common.placeholder.email": "user@example.com",
    "admin.common.placeholder.segment": "kid-girl",
    "admin.common.placeholder.emails": "email1,email2,email3...",
    "admin.common.placeholder.title": "Название",
    "admin.common.placeholder.body": "Сообщение...",
    "admin.common.placeholder.description": "Короткое описание",
    "admin.common.placeholder.iconUrl": "printer или /icons/printer.svg",
    "admin.common.placeholder.url": "https://...",
    "admin.common.placeholder.tags": "tag1, tag2",
    "admin.common.placeholder.serviceType": "http/postgres/s3",
    "admin.common.placeholder.tier": "tier-1",
    "admin.common.placeholder.lifecycle": "active/deprecated",
    "admin.common.placeholder.classification": "internal/PII",
    "admin.common.placeholder.runbookUrl": "https://runbook...",
    "admin.common.placeholder.accessPath": "Запрос доступа / группа",
    "admin.common.placeholder.dependsOn": "service-a, service-b",
    "admin.common.placeholder.ownersJson": "{\"team\":\"core\",\"primary\":\"a@b.com\"}",
    "admin.common.placeholder.linksJson": "{\"docs\":\"...\",\"repo\":\"...\"}",
    "admin.common.placeholder.endpointsJson": "[{\"type\":\"http\",\"url\":\"https://...\"}]",
    "admin.members.title": "Участники",
    "admin.members.add": "Добавить участника",
    "admin.members.none": "Участников пока нет.",
    "admin.members.importDone": "Импортировано участников: {count}",
    "admin.members.until": "до {date}",
    "admin.members.selectSpaceError": "Выберите пространство",
    "admin.content.directory": "Каталог",
    "admin.content.noneDirectory": "Элементов каталога пока нет.",
    "admin.content.createdDirectory": "Элемент каталога создан",
    "admin.content.updatedDirectory": "Каталог обновлён",
    "admin.content.deletedDirectory": "Элемент каталога удалён",
    "admin.content.confirmDeleteDirectory": "Удалить элемент каталога «{title}»?",
    "admin.dashboard.templates": "Шаблоны дашборда",
    "admin.dashboard.blocksCount": "Блоков: {count}",
    "admin.dashboard.editBlocks": "Изменить блоки",
    "admin.dashboard.editor": "Редактор дашборда",
    "admin.dashboard.preview": "Предпросмотр",
    "admin.dashboard.blocks": "Блоки",
    "admin.segment": "Сегмент",
    "admin.segmentSaved": "Сегмент обновлен",
    "admin.reload": "Перезагрузить конфиг",
    "admin.reloading": "Перезагрузка...",
    "admin.reloadDone": "Конфиг перезагружен",
    "admin.reloadFailed": "Не удалось перезагрузить конфиг",
    "app.saveDone": "Сохранено",
    "app.saveFailed": "Не удалось сохранить",
    "space.picker.title": "Пространства",
    "space.picker.subtitle": "Переключайте контекст",
    "space.picker.results": "Результаты",
    "space.picker.recents": "Недавние",
    "space.picker.pinned": "Закрепленные",
    "space.picker.all": "Все пространства",
    "space.picker.pin": "Закрепить",
    "space.lock": "Блокировка пространства",
    "dashboard.empty.title": "Дашборд пока не настроен",
    "dashboard.empty.body": "В baseline v1 сначала должны быть видны ориентация и curated entry points, а уже потом глубокая кастомизация.",
    "resource.noPinned": "Закрепленных ресурсов пока нет",
    "resource.noActivity": "Активности пока нет",
    "resource.copied": "Скопировано",
    "resource.copyFailed": "Не удалось скопировать",
    "resource.actionInvoked": "Действие запущено",
    "resource.actionFailed": "Не удалось выполнить действие",
    "resource.publicReadonly": "Публичные пространства доступны только для чтения",
    "resource.details.title": "Детали ресурса",
    "resource.details.overview": "Обзор",
    "resource.details.access": "Доступ",
    "resource.details.actions": "Действия",
    "resource.details.ownership": "Владение",
    "resource.details.links": "Ссылки",
    "resource.details.endpoints": "Эндпоинты",
    "resource.details.service": "Сервис",
    "resource.details.titleField": "Название",
    "resource.details.description": "Описание",
    "resource.details.type": "Тип",
    "resource.details.tier": "Тир",
    "resource.details.lifecycle": "Жизненный цикл",
    "resource.details.primaryLink": "Основная ссылка",
    "resource.details.endpoint": "Эндпоинт",
    "resource.details.region": "Регион",
    "resource.details.bucket": "Бакет",
    "resource.details.console": "Консоль",
    "resource.details.accessPath": "Путь доступа",
    "resource.details.s3": "S3 детали",
    "resource.details.openConsole": "Открыть консоль",
    "resource.details.copyS3": "Скопировать s3://",
    "resource.details.copyCli": "Скопировать CLI",
    "resource.details.noActions": "Действия пока не настроены.",
    "editor.addBlockTitle": "Добавить блок",
    "editor.addBlockBody": "Выберите тип блока, который нужно добавить в дашборд.",
    "editor.blockSettings": "Настройки блока",
    "editor.advanced": "Продвинутая раскладка",
    "editor.advancedHint": "Сырые координаты сетки остаются доступны, когда нужен точный контроль.",
    "editor.showAdvanced": "Показать расширенные настройки",
    "editor.hideAdvanced": "Скрыть расширенные настройки",
    "surface.kids.title": "Безопасный детский вход",
    "surface.kids.subtitle": "Здесь должны оставаться только разрешённые и понятные вещи.",
    "surface.kids.safeTitle": "Ограничено по умолчанию",
    "surface.kids.safeBody": "Дети видят более спокойную поверхность с меньшим выбором и без операторских элементов управления.",
    "surface.kids.allowedTitle": "Разрешено сейчас",
    "surface.kids.allowedBody": "Эти входы подготовлены для безопасного использования без лишней навигации.",
    "surface.kids.helpTitle": "Если что-то недоступно",
    "surface.kids.helpBody": "Сообщения должны оставаться мягкими и понятными. Если чего-то важного не хватает, нужен взрослый или оператор.",
    "surface.admin.title": "Операторская поверхность контроля",
    "surface.admin.subtitle": "Состояние, риск и следующий шаг важнее списка инструментов.",
    "surface.admin.backupTitle": "Состояние резервных копий",
    "surface.admin.backupBody": "Точка входа к резервным копиям должна быть видна с первого экрана, чтобы восстановление не начиналось с догадок.",
    "surface.admin.updateTitle": "Готовность к обновлению",
    "surface.admin.updateBody": "Перед изменениями проверьте готовность к откату и критичные сервисы, которые обязаны пережить обновление.",
    "surface.admin.criticalTitle": "Критичные сигналы",
    "surface.admin.criticalBody": "Проблемы должны подниматься выше обычных ссылок. Если ничего критичного нет, Atrium должен сказать это спокойно.",
    "surface.admin.recoveryTitle": "Действия для восстановления",
    "surface.admin.recoveryBody": "Оператору нужен следующий шаг: резервные копии, наблюдаемость, вход и понятный путь к восстановлению.",
    "surface.shopping.title": "Shopping-сводка",
    "surface.shopping.subtitle": "Что купить, что в текущем batch и что недавно закрыто должно быть видно прямо внутри Atrium.",
    "surface.shopping.loadingTitle": "Загружаем shopping-состояние",
    "surface.shopping.loadingBody": "Atrium читает текущий shopping snapshot.",
    "surface.shopping.errorBody": "Shopping-сводка временно недоступна. Для диагностики откройте подробный экран.",
    "surface.shopping.needsTitle": "Нужно купить",
    "surface.shopping.needsValue": "{count} активных потребностей",
    "surface.shopping.emptyNeedsTitle": "Активных потребностей нет",
    "surface.shopping.emptyNeedsBody": "Активных purchase intent пока нет.",
    "surface.shopping.runTitle": "Текущий run",
    "surface.shopping.runValue": "{count} позиций · {actionable} actionable",
    "surface.shopping.emptyRunTitle": "Активного run нет",
    "surface.shopping.emptyRunBody": "В текущем shopping batch пока ничего нет. Новый run появится автоматически, когда ты добавишь первую позицию.",
    "surface.shopping.closedTitle": "Недавно закрыто",
    "surface.shopping.closedValue": "{count} закрыто недавно",
    "surface.shopping.emptyClosedTitle": "Недавно ничего не закрыто",
    "surface.shopping.emptyClosedBody": "Здесь видны только купленные и снятые позиции. Отложенный остаток остаётся в истории run.",
    "surface.state.ready": "Готово",
    "surface.state.review": "Нужна проверка",
    "surface.state.clear": "Критичных сигналов нет",
    "surface.state.attention": "Нужно внимание",
    "surface.state.guided": "Есть следующий шаг",
    "surface.action.openResource": "Открыть ресурс",
    "surface.action.openAdmin": "Открыть панель администратора",
    "surface.action.openShopping": "Открыть shopping",
    "surface.action.refreshShopping": "Обновить",
    "surface.action.queueShoppingNeed": "В список",
    "surface.action.closeShoppingRun": "Закрыть run и отложить остаток",
    "block.type.resourcesPinned": "Закреплённые ресурсы",
    "block.type.text": "Текст",
    "language.title": "Язык",
    "performance.title": "Производительность",
    "performance.auto": "Авто",
    "performance.low": "Низкая",
    "performance.normal": "Обычная",
    "role.switch": "Сменить роль",
    "role.actingAs": "Сессия администратора • роль {role}"
  }
};

export const BLOCK_TYPES = {
  resourcesPinned: "core.resources_pinned",
  text: "core.text"
};

export const BLOCK_TYPE_OPTIONS = [
  { value: BLOCK_TYPES.resourcesPinned, label: "Pinned resources" }
];

export const BLOCK_TYPE_CARDS = [
  {
    value: BLOCK_TYPES.resourcesPinned,
    label: "Pinned resources",
    description: "Quick access links and resources.",
    icon: Bookmark
  }
];
